spaship/spaship

packages/cli/README.md, packages/cli/test/commands/deploy.test.js, packages/cli/test/commands/init.test.js
This adds some links from the cli package's README and test files that point back to oclif's testing documentation.
This is to help prevent any confusion about how to write the tests.  Such confusion would be understandable because the
cli uses a different testing system than the rest of the packages.
=> docs(cli): add links back to oclif's testing tools

packages/sync-service/.gitignore, packages/sync-service/README.md, packages/sync-service/config.js, packages/sync-service/lib/db.apikey.js, packages/sync-service/lib/db.apikey.test.js, packages/sync-service/lib/db.js, packages/sync-service/package-lock.json, packages/sync-service/package.json
I was eager to work on the database and API key features so I put together this PR.
It adds:
1. a new module, `sync-service/lib/db` which creates a connection to a mongodb database
2. a new module, `sync-service/lib/db.apikey` which connects to a collection named "apikeys" in the database
3. handy CRUD functions for API keys: `getKeysByUser, getUserByKey, createKey, deleteKey`
4. tests for the `db.apikey` module (`db` should get some too, I just didn't have the time tonight)
5. the [mongo-mock](https://github.com/williamkapke/mongo-mock) module to use during development.  It creates an
in-memory mongo mock so nobody has to set up a real mongodb in their dev environments.  It's extremely convenient.
6. configuration properties for each of these features (see README)
=> add a mongo database with apikey helpers

packages/api/lib/db.js, packages/api/lib/db.mock-mongo.js, packages/api/lib/db.real-mongo.js
The code to connect to (real) mongodb was broken and the SPAship API only worked in "mocked mongodb" mode.  This fixes
the connection to real mongodb servers and separates the real implementation from the mock one (previously they were in
the same file).
=> fix(api): fix connection to mongodb

packages/manager/package.json
The [CRA](https://create-react-app.dev/) is using `homepage` to setup `publicPath`.
https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths
The current config will make all static files path be `./static/xxx.js/css`.
If the url is `https://xxx.com/aaa/aaa`, the static files will return 404 error.
so remove `homepage`
=> fix(manager): use the default '/' root path to avoid path 404 error

packages/api/lib/db.apikey.js, packages/api/lib/db.apikey.test.js
Replace shortid with uuidv4 for generating API keys, for reasons outlined in https://github.com/spaship/spaship/pull/204#issuecomment-595912661
=> feat(api): use UUID v4 format for API keys

packages/api/README.md, packages/api/config.js, packages/api/lib/db.js, packages/api/lib/db.mock-mongo.js, packages/api/lib/db.real-mongo.js
This renames some config properties to enable namespaced config objects.  Here's a before and after with examples.
**Before**
These configuration values (provided as envs):
SPASHIP_MONGO_URL="your.mongo.db:27017"
SPASHIP_MONGO_USER="mongo_user"
SPASHIP_MONGO_PASSWORD="mFk7Pj3efPVNHWrr"
SPASHIP_MONGO_DB="spaship-db"
SPASHIP_MOCK_DB="false"
Would generate this config object:
```js
{
mongo_url: "your.mongo.db:27017",
mongo_user: "mongo_user",
mongo_password: "mFk7Pj3efPVNHWrr",
mongo_db: "spaship-db",
mock_db: false
}
```
Which we can interact with in our code with calls like:
```js
config.get("mongo_user");
config.get("mock_db");
```
There are advantages to having a "flat" config object, but disadvantages too, such as namespacing (ex: `mongo_`) being
implicit in the property names rather …
=> refactor: rename and namespace config properties

packages/api/lib/metadata.js, packages/api/lib/metadata.test.js
Invalid: start with . or _. or include . in the middle
#239 
https://regexper.com/#%5E%28%3F!%5B_%5C.%5D%29%5Ba-zA-Z0-9%5C_%5C-%5D*%24
=> fix(api): exclude invalid spa paths

packages/api/README.md
Added bash as code-fence type within README to fix lint warnings.
=> docs(README): Fixed code-fencing lint warnings.

package-lock.json, package.json, packages/api/package-lock.json, packages/cli/package-lock.json, packages/manager/package-lock.json, packages/router/package-lock.json
If you go to [security](/spaship/spaship/network/alerts) board, you will found we have 4 alerts
* hoek
* minimist
`hoek` is depdency of `oidc`. it should be removed. but not removed in package-lock.json
`minimist` is the dependency of many upstream lib.  regenerate package-lock could update more libs
=> chore: regenerate all package-lock.json

CODE_OF_CONDUCT.md
Created Contributor's Code of Conduct document based upon the Contributor Covenant.
#63 
Created a `CODE_OF_CONDUCT.md` document based upon the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html).
No
=> docs(#63): Add Contributor Code of Conduct document

packages/common/lib/logging/pino-config.js
There has a dependency missing error
```
Error: Missing `pino-pretty` module: `pino-pretty` must be installed separately
881     at getPrettyStream (/usr/local/share/.config/yarn/global/node_modules/pino/lib/tools.js:187:11)
882     at normalizeArgs (/usr/local/share/.config/yarn/global/node_modules/pino/lib/tools.js:347:16)
883     at pino (/usr/local/share/.config/yarn/global/node_modules/pino/pino.js:78:28)
884     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@spaship/common/lib/logging/pino.js:14:13)
```
We should keep use "json" as default, if someone need pretty format, they could install by theirself
<details>
</details>
=> fix(common): use json format as default

packages/manager/src/serviceWorker.ts
Fixes #335 
As per https://github.com/facebook/create-react-app/pull/8272 this issue was caused by a missing catch block in the ServiceWorker unregister() method. Adding that fixed the issue.
No
=> fix(#335): Added catch block to serviceWorker unregister method.

packages/manager/src/components/application/AddApplication.tsx
Resolves #328 
Added PFE inline alert component to `AddApplication.tsx` page with the following text:
> This form is not the recommended way of deploying an application. Please go through the SPAship [CLI](https://github.com/spaship/spaship/blob/master/packages/cli/README.md) and [API](https://github.com/spaship/spaship/blob/master/packages/api/README.md) documentation for the recommended method of deploying your application.
No
=> fix(#328): Added warning message to Deploy UI page.

packages/manager/src/layout/PageToolbar.tsx
Resolves #353 
Added `hrefs` to https://github.com/spaship/spaship/blob/master/README.md and https://github.com/spaship/spaship for the Documentation and Github links under the Page Toolbar.
No
=> chore(#353): Enabled Docs and GH links for Manager Page Toolbar.

packages/router/index.js, packages/router/package-lock.json
Fixes #364
Fixes redirect loop at root path /
No
=> Fixes #364 - redirect root at root path spa

packages/manager/src/components/user/LoginPage.tsx
Resolves #365 
Added SPAship definition and Footer info to the `/login` page.
No
=> fix(#365): Added SPAship definition & Footer info to SPAship login page.

package-lock.json, package.json, packages/manager/package-lock.json
Fixes #440
Downgraded jest to `24.9.0` which was the last stable version. Regenerated package-locks.
No
=> fix(#440): Fixed babel-jest dependency error.

packages/manager/src/components/authentication/APIKeyList.tsx, packages/manager/src/components/authentication/APIKeySubTable.tsx, packages/manager/src/components/authentication/APIKeyTable.tsx
Fixes #439 
Updated the `afterDelete` method to update the API Keys list by deleting the environment entry from the old key by comparing the Label and Environment. In case there is only one environment within the API Key item, remove the entire item
No
=> fix(#439): Fixed API Key deletion behaviour.

packages/manager/src/components/authentication/APIKeyTable.tsx
Fixes #422 
Converted `Expires At` timestamp to DateString.
No
=> feat(#422): Prettified Timestamp for APIKeys page.

.github/PULL_REQUEST_TEMPLATE.md
There's no need to have this.  Tests passing are enforced by github before a PR can be merged.
=> chore: remove "Did the tests pass?" from PR template

packages/api/controllers/apiKey.js, packages/api/services/apiKeyService.js, packages/api/utils/cryptoUtil.js, packages/manager/src/keycloak.ts, packages/manager/src/layout/HeaderTools.tsx, packages/manager/src/layout/UserStatus.tsx
Apply the appropriate type to a few JWT references that were typed as `any`.
=> refactor: apply proper type to SPAship's JWT

packages/manager/tsconfig.json
fixes #867
Resolves the Manager build error:
```
TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible
```
It seems that CRA (or maybe typescript itself?) wants to add the noFallthroughCasesInSwitch property to tsconfig.json
automatically, but it fails.  To workaround that, I added it manually.
No
=> fix: resolve noFallthroughCasesInSwitch typescript error

packages/cli/README.md
It looks like the CLI's README has some problem last time it was regenerated (this happens during both the
`preversion` and `prepack` scripts), leading to
none of the CLI commands being described in the README.  I re-ran the `oclif-dev readme` command to restore the info.
No
=> chore: regenerate cli README

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js
The last release was 5 months ago, and since then, support for the `ARCHIVE` CLI argument was broken.  I think it's
related to the `buildDir` change, which checks for the existence of a buildDir, but the logic was flawed, and resulted
in an error being thrown when `buildDir` was missing but `ARCHIVE` was present.  This fixes that omission and restores
the `ARCHIVE` argument.
No
=> fix(cli): restore support for ARCHIVE argument

packages/cli/src/commands/deploy.js
Explains what a "SPA archive file" is, when you run `spaship help deploy`.
=> docs: explain what an archive file is in the SPAship CLI help

packages/api/package.json, packages/manager/package.json, packages/router/package.json, packages/sync/package.json, scripts/start.sh
Currently, the `npm start` scripts at the monorepo root, and in the api, manager, sync, and router, all require a `.env`
file be present at the root of the repo.  This is unintentional and this PR makes the `.env` file optional.
No.
=> fix: make the .env file optional for npm start

packages/common/lib/config/validate.js
#455 added support for a `buildDir` property in spaship.yaml.  Today, I discovered that the spaship.yaml schema which
is used to check for valid spaship.yaml files, wasn't updated.  This PR adds support for `buildDir` so the API will stop
throwing errors about invalid spaship.yaml.
One remaining question is "how was this not caught?"  I have no idea!  I just know that when I try to deploy using the
latest CLI and API, the API returns an error about invalid spaship.yaml file because it contained an unknown property:
`buildDir`.  This PR fixes that issue.
No
=> fix(api): accept buildDir in spaship.yaml

packages/api/middlewares/authentication.js, packages/api/middlewares/checkAccess.js
It seems that #858 caused a regression that made API key auth unusable, because it couldn't pass the "user belongs to
required group" check.  I didn't catch it while reviewing that PR, but discovered it when working on the CLI later.
Here's a fix.  If an API key exists, we know it was created by a user who belonged to the required group.
No.
=> fix: repair regression causing API key auth to be unusable

packages/cli/src/common/zip.js
I was attempting to deploy a SPA whose package name (package.json `"name"`) was inside an npm org such as
`"@orgname/packagename"`.  It failed because the `/` was interpreted as a directory separator, and the buildDir code
attempted to write the zip file into the nonexistant directory.  This PR fixes the issue by simply replacing `/` with
`_` in package names.
No
=> fix(cli): allow using buildDir for @org pkgs

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/src/commands/deploy.js
feat(cli): add --path flag
#933
This adds `--path` support to the `spaship deploy` command.  I could have _sworn_ we already had this feature, but I was
wrong!  Adding it now.
Please note: I have NOT yet tested this PR against the API
No.
Well, kind of yes.  It changes some code added in #477 which allowed `path` to be defined in spashiprc.  In my eyes,
this was an unintended change, and spashiprc was never meant to store `path`.  This PR changes the code so that `path`
can be defined in spaship.yaml, or in the `--path` flag of `spaship deploy`, and nowhere else.  The ability to define
`path` in spashiprc was never advertised or documented, so I don't truly consider this a breaking change.  It's unlikely
anyone made use of it, but we should check with some devs like @gautamkrishnar!
=> feat(cli): add --path flag

packages/api/middlewares/authentication.js, packages/api/services/apiKeyService.js
fixes #969
#969 explains the problem.  This PR fixes it by changing the API key parsing function to stop treating every request
like an API key request.
It also makes a _very_ minor improvement: extra whitespace around the api key in the authorization
header is now tolerated, so `Authorization: APIKey         ABCDEFG  ` would be not fail due to the extra spaces.
No.
=> fix(auth): restore JWT authentication

package-lock.json, package.json
reverts jest to v26.6.0 to fix the jest version mismatch error being thrown by the manager app.
No
=> chore(deps): fixes jest version mismatch

packages/common/lib/config/append.test.js, packages/common/lib/config/mockDataTests/common.config.read/spaship.yaml, packages/common/lib/config/read.js, packages/common/lib/config/read.test.js
feat(common): support (yaml, yml, YAML, YML) config files (#873)
#873 
- Makes common.config.read to support yaml extension variations (yaml, yml, YAML, YML) by default.
- If user wants to read exact filepath they can call `common.config.read(filepath, { checkExtensionVariation: false }`
- Adds unit tests
No
<details>
</details>
=> feat(common): support (yaml, yml, YAML, YML) config files (#873)

packages/common/lib/config/append.test.js, packages/common/lib/config/read.js, packages/common/lib/config/write.js
Fixes #1129 
replaces safe(Dump/Load) methods with the default methods within the common.read, common.write and test configurations.
No
=> fix(#1129): replaces safe(Dump/Load) methods with the default methods.

packages/cli/src/services/deployService.js, packages/cli/test/services/deployService.test.js
Fixes #1145 
Enables `http` based API endpoint support and updates the deployment service test definitions. 
No
=> feat(#1145): enables `http` based API endpoint support and updates the deployment service test definitions. 

packages/router/package.json
Set the default value of `max-http-header-size` to 16kb
No
=> feat(router): Increase max http header size to 16kb.

packages/cli/README.md, packages/cli/src/commands/deploy.js
#1325
- added `--builddir` as CLI argument for deploy command
No
<details>
</details>
=> feat(#1325): added `--builddir` as CLI argument for deploy command

packages/sync/lib/autosync.js, packages/sync/package-lock.json, packages/sync/package.json
When the sync service is given a querystring in a target's configuration, it's not correctly handling querystrings.  The
code is using a package called `url-join` to join subpaths to the main URL, but the package apparently doesn't know how
to handle querystrings.  I've removed the package and replaced it with node's built-in `URL`.
No.
=> fix sync service's querystring handling

packages/manager/components/web-property/spaProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json
- Corrected names for spa path and url in the SPA list page
- No
<details>
</details>
=> hot-fix(spa-list-page) - Corrected names for spa path and url

packages/manager/components/settings/envList.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/pages/api/delete/apiKey.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/utils/api.utils.ts, packages/manager/utils/endpoint.utils.ts
-  Delete apikey button added to the manager (settings page)
- Spinner issues resolved for the error in creating webproperty
- Handled 404 error (apikey)
- Delete api key button added into manager
- Modal will popup while you click on the delete button
- Next API & Orchestrator url added into endpoint
- Delete API Key Service added 
- Error handled for "Issue while property creation"
- Alert added if property creation failed
- 404 error handled in api.util
- No API Key present issue resolved
- No
=> feat(manager) : delete api key feature & spinner fix

packages/api/controllers/apiKey.js, packages/api/controllers/operatorServices/operations/saveAlias.js
- No Env Creation exception handled
- Error code added for apikey list
- If no env is created for multiple reason (db issue, no deployment connection string present, operator outage etc), then it will be handled in the api end, and throw issues in FE
- 404 error code added if no api key found
- No
=> fix(api) : webproperty creation issue resolved

packages/api/app.js, packages/api/index.js
- Rate limit set to 10
- Rate limit for deployment API set to 10
- No
=> fix(api) : max limit set to 10 for deployment api/min

packages/cli/src/commands/deploy.js
SPASHIP-993
Currently lets say that we are developing a react application, by default react uses "/build" to generate its distribution files. Assume that the following is my spaship.yaml file
```yaml
name: my-awesome-app
path: /application
single: true
buildDir: /dist
```
The above yaml is technically wrong since it points to /dist instead of /build. When we use spaship cli to deploy our app, it will show success message regardless of the above problem.
This PR will add a check for the buildDir and causes the SPAShip CLI to exit immediately if it doesn't exists.
No
n/a
=> fix(SPASHIP-993): added check for buildDir before archiving

packages/manager/src/views/WebPropertyEnvPage/components/CreateAPIKeyForm/CreateAPIKeyForm.tsx
1. fixed calender date going out of screen
No
<details>
</details>
=> fix(manager): fixed calender date going out of screen

packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/EmptyInfo/EmptyInfo.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
1. Fixed label in property
2. Added end range in line chart
3. Fixed search not working with space
4. Fixed broken empty info url
No
<details>
</details>
=> fix(manager): added end range in line chart and broken image url

packages/operator/pom.xml, packages/operator/src/main/java/io/spaship/operator/api/EnvironmentController.java, packages/operator/src/main/java/io/spaship/operator/api/EventStream.java, packages/operator/src/main/java/io/spaship/operator/api/SpaDeploymentController.java, packages/operator/src/main/resources/META-INF/resources/index.html, packages/operator/src/main/resources/application.properties
Authentication support for the operator
OIDC setup is enabled from the app configuration, and sensitive APIs are now auth protected.
Yes
Without an OIDC access token, the orchestrator (middleware) can't access the operator's API, and doing so will result in 401 errors. 
</details>
=> Authentication support for the operator

packages/api/controllers/operatorServices/operations/getEphList.js, packages/api/controllers/operatorServices/operations/saveAlias.js
- Changes in Response for Eph Records
- Validation added for Alias
- SPA response added into eph records (spa mapped with eph env)
- Mapper added for Eph Records 
- Validations added for Env & PropertyName while creation
- Length set for PropertyName is 50, & env is 25.
No
<details>
</details>
=> feat(api) : changes in response for EPH preview 

packages/operator/src/main/java/io/spaship/operator/api/EnvironmentController.java, packages/operator/src/main/java/io/spaship/operator/service/k8s/Operator.java, packages/operator/src/main/java/io/spaship/operator/service/k8s/SideCarOperations.java
Manually triggering the sync on sidecar container restart.
When scheduling sync from the sync API, the operator updates the sync config of the specific environment and adds the updated sync JSON so that on the next restart, the sidecar container automatically picks up the sync from the config and schedules the Sync.
No
=> feat(operator): Auto update env specific sync config when it is scheduled through the operator's sync api.

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Fixing zoom on scroll issue in the deployment graph. Added ChartVoronoiContainer to the graph lines. Changed the x-axis values from weeks to absolute dates
No 
<details>
</details>
=> fix(manager): Change date format and fix zoom behaviour on dashboard graph

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
Fixes the bug where filter was not visible in web property where we have envs with spas and no spas.
No
<details>
New web property/ only ephemeral view deployed : no filter should be visible
spas are deployed on other envs and not on one envs : Filter should be visible
</details>
=> fix/prop-page(manager) : Changes in web property instruction page: Env filter visible in web property depending on whether spas are deployed or not

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Syncing the graph legend color to the color of lines. Putting prod instead of UAT prod in the graph. 
No 
<details>
</details>
=> fix(manager): Fixing the Line chart color inconsistency issue

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Pluralized the heading titles and sorted the date ordering in dashboard graph.
No 
<details>
</details>
=> fix(manager): minor bug fixes in the dashboard section

packages/api/src/server/permission/service/permission.service.ts
Subject:  fix(api) : activity stream fixed for RBAC Creation
1. Duplicated Records issue resolved for activity stream on Permission creation
2. Add only Newly Created Permissions in the Activity Stream
3. Activity stream message formatted
NO
<details>
</details>
=> fix(api) : activity stream fixed for RBAC Creation

packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
Show empty box instead of 0 on false values of average deployment time in dashboard analytics.
No
=> fix(manager): handling falsy values in analytics

packages/manager/src/services/webProperty/types.ts, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx, packages/manager/src/views/WebPropertyListPage/components/WebPropertyCard/WebPropertyCard.tsx
Domain is mentioned for property over individual boxes for Property. (Web Properties page).
- In a Web property, we can have multiple Environments with mapped domains / hosted urls.
- Mentioned domain of Prod in most cases, if no prod environment then stage is shown.
- In case there is neither prod nor stage the first env present in the list is shown.
No
=> feat(manager) : Added domains for each property on Web Property List Page

packages/api/src/configuration/index.ts, packages/api/src/main.ts, packages/api/src/server/health/service/health.module.ts
Subject:  feat(api) : CORS configs added into env
1. Read cors config from the env varaibles
2. Used the existing cors config, localhost:2468 (manager) set to default
3. Lint fixed
NO
<details>
</details>
=> feat(api) : CORS configs added into env

packages/api/src/configuration/index.ts, packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/auth/auth.guard.ts
Subject:  feat(api) : deployment hour saved api added for the login screen
1.  Deployment hour saved api (get) added for the login screen
2. As login screen doesn't have any auth, so we've removed the auth for this specific api (only send the hours)
NO
<details>
</details>
=> feat(api) : deployment hour saved api added for the login screen

packages/api/src/configuration/index.ts, packages/api/src/server/agenda/agenda.module.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.module.ts, packages/api/src/server/environment/service/environment.module.ts, packages/api/src/server/property/service/property.module.ts, packages/api/src/server/property/service/property.service.ts
Subject:  chore(api) : cmdb code validation & default code process, eph env duration limit
1. Set CMDB default code as SPAS-001 if cmdb code is note preset
2. Check CMDB code every time before creating a property 
3. Maximum duration for Eph Env set to 500 hrs
NO
<details>
</details>
=> chore(api) : cmdb code validation & default code process, eph env duration limit

packages/api/src/server/analytics/service/analytics.service.ts
Subject:  chore(api) : change date frame for the the monthly analytics
1. send the date frame where analytical data doesn't exist
2. to be removed once patternly issue is reosolved from the SPAship maanger
NO
<details>
</details>
=> chore(api) : change date frame for the the monthly analytics

packages/api/src/server/lighthouse/service/factory.ts, packages/api/src/server/lighthouse/service/index.ts
Subject:  fix(api) : get single response for the lighthouse report
1. Get single response for the lighthouse report
2. lhBuildId replaced buildId added to the skip specfier
NO
<details>
</details>
=> fix(api) : get single response for the lighthouse report

packages/manager/src/services/lighthouse/queries.tsx, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ApplicationStatus.tsx
1. First load of data in spa detailed page was not coming for both static and containerized builds
2. Fixing application down status for both access and router urls
<details>
</details>
=> feat(Manager): Fixed issue of first of data for SPA detailed and lighthouse page | Application status bug resolved

.github/workflows/api-ci.yaml, packages/api/Dockerfile
Introduced optional `tagsuffix` and `ugroup` inputs to the API GitHub Action. The `tagsuffix` is appended to the image tag if set, enhancing versioning flexibility. The `ugroup` input serves as a build argument for specifying a user group in the Dockerfile, with a provision to leave it blank for default assignment. This update addresses environment-specific user range discrepancies, offering a more adaptable build configuration.
Manual changes in docker file every time
No
=> feat: Add optional tagsuffix and ugroup inputs to GitHub Action for orchestrator

packages/manager/src/views/HomePage/components/WebpropertiesTable/DeploymentStatsCard.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment/CreateStaticApp/CreateStaticApp.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment/StaticSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/VirtualPath/VirtualPath.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/AddDeployments.tsx
1. Reorder Tabs for Web Properties and SPA Page: Swap the positions of the History and Settings tabs so that the Settings tab is the final tab in the tab list for both web properties and the SPA page.
2. Add Asterisk for Required Fields in Starting Deployment Form: Add an asterisk (*) to indicate required fields in the starting deployment form.
3. Pre-populate Application Name in Static Deployment Form: Automatically fill in the application name field in the static deployment form.
4. Handle Symlink and No Virtual Path Empty State: Implement handling for scenarios with a no Symlink and no virtual path, ensuring a proper empty state is displayed.
<details>
</details>
=> feat(Manager): UI Enhancements and Form Improvements

.github/workflows/router.yaml, ContainerFile-router, packages/router/index.js
This PR introduces a new GitHub Action workflow to automate the building and pushing of the SPAship router container image to our Quay.io registry. This action parallels our existing workflow for the SPAship api service.
- Created a new workflow file: `.github/workflows/router-build-push.yml`
- Configured the action to use the `ContainerFile-router` for building the image
- Set up authentication and pushing to Quay.io registry
- Implemented dynamic tagging based on git refs and optional inputs
- Enabled manual triggering with customizable options
- This action assumes `ContainerFile-router` is in the root directory of the repository
- The workflow uses the same secret management as the existing API workflow
=> feat(router): add GitHub Action for building and pushing SPAship router image

packages/api/src/server/application/service/index.ts
Subject: override files during extracting and zipping applications
1. This PR introduces commands to ensure files are overwritten during the extraction process using 7-Zip. The commands use the `-aoa` (Overwrite All) option to automatically overwrite existing files without prompting.
NO
<details>
</details>
=> chore(api) : override files during extracting and zipping applications
