spaship/spaship

packages/path-proxy/README.md, packages/path-proxy/config.js, packages/path-proxy/config.json.example, packages/path-proxy/index.js, packages/path-proxy/index.test.js, packages/path-proxy/package-lock.json, packages/path-proxy/package.json
=> feat(path-proxy): make path-proxy configurable

packages/path-proxy/package-lock.json
path-proxy's lockfile needed to be regenerated.  Not sure why renovate didn't take care of this.
=> regenerate path-proxy lockfile

packages/api/nodemon.json
Created `nodemon.json` and added `mock-db.js` to it's "ignore" list.
=> Added nodemon conf to ignore mock-db.

packages/api/README.md, packages/api/config.js, packages/api/lib/db.js
=> feat(api): add mongodb user & password config

packages/manager/src/App.tsx, packages/manager/src/Routes.tsx, packages/manager/src/components/user/LoginPage.tsx
Small PR that cleans up some unused variable warnings.
=> refactor: clean up some TS lint warnings

packages/manager/public/.htaccess
=> fix(manager): add .htaccess make react browser route work

packages/manager/src/components/application/ApplicationFilter.tsx, packages/manager/src/components/application/ApplicationList.tsx, packages/manager/src/components/authentication/APIKeyIndex.tsx, packages/manager/src/components/general/ConfirmButton.tsx, packages/manager/src/components/user/LoginForm.tsx, packages/manager/src/layout/UserStatus.tsx
=> chore(manager): add id to some elements for testing purpose

packages/api/lib/background/autosync.js, packages/api/lib/metadata.js, packages/api/lib/metadata.test.js
=> feat(api): add timestamp for list api

packages/api/README.md
Added the missing bash identifier to a code-fence section.
=> docs(README): Fixed remaining code-fence lint issues

.travis.yml, README.md, package-lock.json, package.json
Add code coverage service `codecov` for spaship
More details in https://codecov.io/gh/spaship/spaship
<details>
</details>
=> chore: add codecov

packages/cli/src/commands/deploy.js
Fix #316 
<details>
</details>
=> fix(cli): send "name", "path" to API

packages/api/models/apiKey.js
This PR is part of #319 
<details>
</details>
=> fix(api): expiredDate should not before today

packages/api/models/apiKey.js
The `apiKey` label should only unique in user's scope.
<details>
</details>
=> fix(api): apiKey label should unique by userId

packages/cli/src/commands/deploy.js
=> fix(cli): duplicate path

packages/api/routes/applications.js
=> fix(api): upload was use wrong name

packages/api/openapi.yml
=> docs(api): fix upload in openapi doc

packages/api/openapi.yml, packages/manager/src/components/authentication/APIKeySubTable.tsx
Fix #327 
<details>
</details>
=> chore(manager): rename apiKey revoke to delete

e2e/manager/package-lock.json, e2e/manager/package.json, package-lock.json
Rebuilt package-locks to fix npm audit issues.
=> fix(npm-audit): Fix npm audit vulnerabilities.

packages/manager/src/services/APIService.ts
Resolves #267 
Implemented [keycloak.updateToken](https://www.keycloak.org/docs/latest/securing_apps/index.html#updatetoken-minvalidity) for refreshing tokens prior to making an API call in case the token is about to expire within the next 30 secs.
No
=> feat(#267): Added JWT refresh to APIService methods.

packages/api/README.md
Resolves #164 
Updated API Documentation for API Keys and also added cURL examples
No
=> docs(api): Updated API documentation with cURL examples.

.gitignore, packages/router/.gitignore, packages/router/README.md, packages/router/config.js, packages/router/index.js, packages/router/index.test.js, packages/router/jest.config.js, packages/router/package-lock.json
Adding root path spa support to router.  
Fixes #329
=> fixes #329 - add root path spa support to router

packages/api/controllers/application.js, packages/api/controllers/application.test.js
Fix #356 
<details>
</details>
=> fix(api): GET application should return details info

packages/common/lib/flatpath/index.js, packages/common/lib/flatpath/index.test.js
Fix #350 
<details>
</details>
=> feat(common): add specific ROOTSPA case

packages/manager/src/components/dashboard/DashboardIndex.tsx
Resolves #359 
Updated the `Coming Soon` message on the Dashboard Page.
No
=> fix(#359): Jazzed up the Coming Soon message on the Dashboard page.

packages/api/controllers/application.js, packages/api/controllers/application.test.js
=> fix(api): #370 return error if app's user not match

packages/manager/src/services/APIKeyService.ts
Fix #373 
<details>
</details>
=> fix(manager): when apiKey generated without any environment name

packages/manager/src/components/application/ApplicationList.tsx, packages/manager/src/components/application/ApplicationTable.tsx, packages/manager/src/components/authentication/APIKeyTable.tsx, packages/manager/src/components/dashboard/DashboardIndex.tsx
Fixes #367 
Fixed the following issues:
- Toolbar alignment across the Application and Authentication pages.
- Alignment of EmptyTable message for ApplicationTable.
- Alignment of EmptyTable message for APIKeyTable.
- Typo in the Dashboard's Coming Soon message.
No
<details>
</details>
=> fix(#367): Fixed multiple minor styling issues across Manager components.

packages/manager/src/Routes.tsx, packages/manager/src/components/user/LoginForm.tsx, packages/manager/src/components/user/LoginPage.tsx
Resolves #362 
Replaced the static `Loading...` text with the existing `EmptySpinner` component.
No
=> chore(#362): Replaced the static loading text with EmptySpinner Component.

packages/api/openapi.yml
=> docs(api): add get application api doc

packages/api/middlewares/authentication.js
Fix #300
all requests with `/v1/apiKeys/*` will use JWT to do validation
<details>
</details>
=> fix(api): #300 apiKeys endpoint can not auth by apiKey

packages/api/controllers/application.js, packages/api/controllers/application.test.js, packages/api/services/fileService.js, packages/api/services/fileService.test.js
Fix #377 
<details>
</details>
=> fix(api): use fileService to find app by name

packages/manager/public/config/manager.js, packages/manager/src/services/ApplicationService.ts
Fix #385 
<details>
</details>
=> fix(manager): show path error in environment details

packages/api/controllers/application.js, packages/api/controllers/application.test.js, packages/api/package-lock.json, packages/api/package.json, packages/api/services/deployService.js, packages/api/services/fileService.js
=> test(api): add unit test for deploy

README.md
=> chore: add travis badge

packages/api/controllers/application.js, packages/api/controllers/application.test.js, packages/api/package-lock.json, packages/api/package.json, packages/api/services/deployService.js, packages/manager/src/components/application/AddApplication.tsx, packages/manager/src/components/application/ApplicationIndex.tsx, packages/manager/src/utils/APIUtil.ts
fix #392 
<details>
</details>
=> fix(api): (#392) deploy same path again should overwrite the previous

e2e/package.json
=> test(e2e): fix tar fixture path error

packages/api/controllers/application.test.js, packages/api/package-lock.json, packages/api/package.json, packages/api/services/deployService.js
The `fs.rmdir` error has been fixed by mock-fs https://github.com/tschaub/mock-fs/issues/292
We could use fs without 3rd party lib
<details>
</details>
=> chore(api): fix ut issues

renovate.json
There still have some weekly update need manual review.
The PR is for auto merge some minor/patch changes. if there has any x/y update, it will need human review
<details>
</details>
=> chore(ci): setup renovate autoMerge, minor/patch updates will be auto merged

packages/api/README.md, packages/cli/README.md, packages/sync/README.md
Fixes #444
Updated all shell snippet tags across all README docs to sh.
No
=> chore(#444): Updated shell snippet tags to sh.

packages/manager/src/services/APIKeyService.ts
Fixes #435 
Fixed shortKey assignment in APIKey Service.
No
=> fix(#435): Fixed shortKey display issue post new key creation.

e2e/cypress/fixtures/test-spa/index.html
=> fix(test): rename init.html to init/index.html

packages/cli/src/commands/deploy.js
#475 
Added `startsWith('/')` check for path to prevent deploying the application to wrong paths. CLI will automatically prefix the path with a `/`.
No
<details>
</details>
=> fix(#475): Added path validation before publishing

packages/manager/public/index.html
Fix #380 
<details>
</details>
=> fix(manager): add timestamp for config script tag to avoid cache issue

package-lock.json, package.json
Fixes #518 
`npm test` was broken at the root level because of a version conflict in eslint.  This changes the eslint dependency to the compatible version
no
=> Fixes #518 - fixes error message when running npm test at root level

README.md
=> Added a very simple getting started section

packages/api/package-lock.json, packages/cli/package-lock.json, packages/manager/package-lock.json, packages/router/package-lock.json, packages/sync/package-lock.json
Updated package-locks and fix audit issues.
No
=> chore(npm): Updated package-locks and fix audit issues.

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js, packages/cli/test/services/deployService.test.js
Fix #520 
<details>
</details>
=> feat(cli): add deploy progress

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js
Makes every dependencies could running on >=8.0.0
Fix #314 
```⠸ Uploading SPA: 50% (2.62 MB/5.29 MB) | 243 kB/s```
<details>
</details>
=> chore(cli): replace `got` to node http module

packages/api/app.js, packages/api/openapi.yml
Fix #474 
<details>
</details>
=> fix(api): remove hardcode api host in OpenAPI

packages/manager/src/components/user/LoginPage.tsx
Fix #499 
<details>
</details>
=> fix(manager): user should not redirect to login page if they already login

packages/manager/src/components/application/ApplicationIndex.tsx
Resolves #495 
Removed 'Purge Cache' button from the Manager app's Application Details page.
No
=> feat(#495): Removed 'Purge Cache' button from Application Details page.

packages/api/services/deployService.js
Fix #523 
<details>
</details>
=> fix(api): avoid overwrite exists .htaccess

packages/cli/src/services/deployService.js
=> fix(cli): undefined req issue

packages/cli/package-lock.json, packages/cli/package.json
=> fix(cli): form-data was missing

packages/manager/package-lock.json, packages/manager/package.json
=> Revert "chore(deps): update dependency @patternfly/react-icons to v4"

packages/manager/package-lock.json, packages/manager/package.json
=> Revert "chore(deps): update dependency @patternfly/react-table to v4"

packages/manager/package.json, packages/manager/public/.htaccess, packages/manager/src/Routes.tsx
=> WIP: chore(manager): move to /manager path

packages/manager/package.json, packages/manager/public/.htaccess, packages/manager/public/config/manager.js, packages/manager/src/Routes.tsx, packages/manager/src/components/application/AddApplication.tsx, packages/manager/src/components/application/ApplicationEnvironmentTable.tsx, packages/manager/src/components/application/ApplicationList.tsx, packages/manager/src/components/application/ApplicationTable.tsx, packages/manager/src/components/authentication/APIKeyCreateModal.tsx, packages/manager/src/components/authentication/APIKeyList.tsx, packages/manager/src/components/authentication/APIKeySubTable.tsx, packages/manager/src/components/authentication/APIKeyTable.tsx, packages/manager/src/components/environment/EnvironmentTable.tsx, packages/manager/src/components/property/NewProperty.tsx, packages/manager/src/components/property/NewPropertyModal.tsx, packages/manager/src/components/property/Property.tsx, packages/manager/src/components/property/PropertyList.tsx, packages/manager/src/config.ts, packages/manager/src/hooks/useConfig.ts, packages/manager/src/keycloak.ts, packages/manager/src/layout/Namespace.tsx, packages/manager/src/layout/PageNav.tsx, packages/manager/src/services/APIKeyService.ts, packages/manager/src/services/ApplicationService.ts
Fix #502 
<details>
</details>
=> feat(manager): #502 enhance manager to be multi-tenant

packages/manager/src/components/authentication/APIKeyCreateModal.tsx
Resolves #513 
Added warning message to the New API Key modal.
No
=> feat(#513): Added warning message to the New API Key modal.

packages/manager/src/components/authentication/APIKeyCreateModal.tsx, packages/manager/src/components/authentication/APIKeyList.tsx
Fix #318 
<details>
</details>
=> fix(manager): #318 disable submit button if use duplicate label

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/application/AddApplication.tsx, packages/manager/src/components/general/Toast.tsx, packages/manager/src/hooks/useNotify.tsx, packages/manager/src/index.tsx, packages/manager/src/layout/Page.tsx, packages/manager/src/static/css/root.css
Fix SPASHIP-55
<details>
</details>
=> feat(manager): add notify when deploy a new spa successful

packages/api/controllers/apiKey.js, packages/api/services/apiKeyService.js, packages/api/utils/cryptoUtil.js
Simply renames 'encrypt' to 'hash', to accurately reflect what the function does.
=> chore: rename encrypt to hash

package-lock.json
=> chore: fix npm audit issues

packages/api/middlewares/authentication.js
Fix #724 
<details>
</details>
=> fix(api): #724 Error: algorithms should be set

packages/manager/src/components/application/ApplicationDetail.tsx
Fix #758 
<details>
</details>
=> fix(manager): can not fetch application details

packages/api/package-lock.json
=> chore(api): fix "bl" security vulnerablity issue

packages/documentation/package.json
Adds a test script to the documentation package.  The test script does nothing more than perform a documentation build.
The purpose is to catch issues like #862 before they get merged.
No
=> test(docs): add a test script for documentation

packages/manager/src/components/authentication/APIKeyCreateModal.tsx, packages/manager/src/services/APIKeyService.ts, packages/manager/src/services/ApplicationService.ts
Fix #861 
<details>
</details>
=> fix(manager): the api key created but not show up

packages/cli/src/commands/deploy.js
Fix #878 
<details>
</details>
=> feat(cli): using api url origin

packages/cli/src/services/deployService.js
fixes #683
This PR tries to provide more helpful error messages in a variety of error conditions.
No.
=> feat: add better error messages to the cli

package-lock.json, package.json, packages/manager/package-lock.json
Fixes npm dependency mismatch issues with eslint, jest and babel-jest
No
=> chore(deps): Fix dependency mismatch errors.

packages/cli/src/commands/deploy.js
Fix #903 #617 
https://oclif.io/docs/commands#thiserrormessage-string--error-options-code-string-exit-number-ref-string-suggestions-string
<details>
</details>
=> fix(cli): add exit code when cli error

packages/api/services/apiKeyService.js, packages/api/services/apiKeyService.test.js, packages/cli/src/services/deployService.js
Since discussed with @mwcz . I'm agree to replace `x-api-key` to `authorization`.
Yes
<details>
</details>
=> chore(apiKey)!: Use Authorization header to send API Key

packages/router/README.md, packages/router/config.js, packages/router/index.js
=> feat(router): add forwarded_host options to support router behind a proxy

packages/common/lib/htaccess/index.js
Fix #1072 
<details>
</details>
=> fix(common): name with whitespace will broke htaccess

packages/manager/src/components/application/ApplicationList.tsx, packages/manager/src/components/application/ApplicationTable.tsx, packages/manager/src/components/authentication/APIKeyList.tsx, packages/manager/src/components/authentication/APIKeyTable.tsx, packages/manager/src/components/general/EmptyAccessDenied.tsx, packages/manager/src/services/APIKeyService.ts, packages/manager/src/services/ApplicationService.ts
Fixes #1108 
Implemented user access checks for the SPAship manager.
No
<details>
- ![image](https://user-images.githubusercontent.com/1418735/111159138-ca585880-85be-11eb-9c8e-6d73fc5bc2a4.png)
- ![image](https://user-images.githubusercontent.com/1418735/111159180-d6441a80-85be-11eb-9476-480918482dda.png)
</details>
=> fix(#1108): Implements access control checks for the SPAship manager

packages/manager/src/App.tsx
Removes unnecessary keycloak log messages from the manager app.
No
=> chore(logs): removes unnecessary keycloak log messages.

e2e/package-lock.json, package-lock.json, package.json, packages/api/package-lock.json, packages/api/package.json, packages/cli/package-lock.json, packages/common/package-lock.json, packages/router/package-lock.json, packages/router/package.json, packages/sync/package-lock.json
Updates dependencies across packages to fix security vulnerabilities 
Potentially Breaking changes which can be tackled in subsequent PRs.
=> chore(deps): Updates dependencies across packages to fix security vulnerabilities 

packages/manager/package-lock.json, packages/manager/package.json
update dependency @types/react-dom to v17
No
=> chore(deps): update dependency @types/react-dom to v17

packages/cli/src/common/zip.js
Replaces read-pkg-up's import statement with require.
No
=> fix(cli): replaces read-pkg-up's import statement with require.

.github/workflows/codeql-analysis.yml
Configured GitHub action for CodeQL Analysis
No
=> feat(codeql): setup codeql analysis

packages/api/services/apiKeyService.test.js, packages/cli/package-lock.json, packages/cli/package.json
Ref: #1112 
Rolls back read-pkg-up to v7.0.1 in cli and removes unnecessary request header console log from API Key Service test cases.
No
=> fix(tests): fixes error messages in test runs

.github/workflows/node.js.yml, package-lock.json, packages/router/index.test.js, packages/router/jest.config.js
Fixes #1112 
Reconfigures GitHub action for Nodejs and disables router tests.
No
=> fix(actions): fixes failing node js github action

packages/api/package.json
Due to this mongoose version, API was breaking.
<details>
</details>
=> fix(deps): mongoose version changed to v5

packages/api/Dockerfile
=> fix (api) : docker file root access issue resolved

packages/api/Dockerfile, packages/api/index.js
=> fix (api) : docker issue fixed

packages/api/package.json
=> fix (api) : start command changed

packages/api/index.js
=> fix (api) : remove log for path

packages/api/Dockerfile
=> fix (api) : clean npm cache for docker

packages/api/Dockerfile
=> fix (api) : remove global npm install

packages/api/Dockerfile
=> fix (api) : checks update added

packages/api/Dockerfile
=> fix (api) : npm-checks-updates added

packages/api/Dockerfile
=> fix (api) : docker optimized

packages/api/Dockerfile
=> fix (api) : docker-npm issue resolved

packages/api/Dockerfile, packages/api/controllers/services/analyticsServiceFilter.js, packages/api/middlewares/checkAccess.js, packages/sync/lib/autosync.js, packages/sync/package-lock.json, packages/sync/package.json
=> fix (api) : ldap user group temporarily disabled for dev

packages/api/controllers/services/analyticsServiceFilter.js
=> fix (api) : activities api issue resolved

packages/api/controllers/application.js, packages/api/routes/applications.js
=> feat (api) : validation api added

packages/api/config.js, packages/api/controllers/application.js, packages/api/utils/multerUtil.js
=> fix (api) : spa upload into operator issue fixed

packages/api/Dockerfile
=> fix (api) : docker dir access issue resolved

packages/api/Dockerfile
=> fix (api) : root directory creation issue

packages/api/controllers/webProperties/analyzeRepository.js
=> fix (api) : git operations path issues

packages/api/controllers/webProperties/analyzeRepository.js
=> fix (api) : root path issue resolved

packages/api/Dockerfile, packages/api/controllers/webProperties/analyzeRepository.js, packages/api/controllers/webProperties/gitOperations.js, packages/api/index.js
=> fix (api) : git operation issues resolved

packages/api/Dockerfile
=> fix (api) : docker syntax issue fixed

packages/api/app.js, packages/api/config.js, packages/api/controllers/application.js, packages/api/controllers/webProperties/gitOperations.js, packages/api/index.js
=> fix (api) : hosted file download path added

packages/api/controllers/application.js
=> fix (api) : validations added for deployment api

packages/api/controllers/webProperties/gitOperations.js
=> fix (api) : validation added for git operation

packages/api/controllers/application.js
=> fix (api) : file param issue resolved

packages/api/controllers/application.js
<details>
sanitize function is throwing error because of dependency issue (removed the sanitize functions(
token validation service added
</details>
=> fix (api) : sanitize issue resolved

packages/api/app.js, packages/api/config.js, packages/api/controllers/application.js, packages/api/controllers/operatorServices/consumeSSE.js, packages/api/models/cliActivities.js
=> feat (api) : sse integrated for the metrics

packages/api/app.js
=> fix (api) : file path issue resolved

packages/api/routes/webProperty.js
=> fix (api) : activity endpoint added

packages/api/config.js, packages/api/controllers/application.js
=> fix (api) : empty description issue resolved

packages/api/config.js, packages/api/controllers/application.js
=> fix (api) : env url changed

packages/api/config.js
=> fix (api) : fix env var for operator

packages/api/controllers/webProperties/gitOperations.js, packages/api/controllers/webProperties/saveWebProperty.js
=> fix (api) : new .spaship config added

packages/api/config.js, packages/api/controllers/operatorServices/consumeEvent.js
=> fix (api) : config issue resolved

packages/api/config.js, packages/api/controllers/application.js, packages/api/middlewares/authentication.js, packages/api/package.json
=> feat (api) : long live token added

packages/api/controllers/application.js
=> fix (api) : deploy api issues resolved

packages/api/controllers/application.js, packages/api/controllers/operatorServices/produceEvent.js, packages/api/controllers/webProperties/analyzeRepository.js, packages/api/controllers/webProperties/getSPAList.js, packages/api/controllers/webProperties/getWebPropertyList.js, packages/api/controllers/webProperties/gitOperations.js, packages/api/middlewares/authentication.js, packages/api/utils/errors/Unauthorized.js
=> fix (api) : error handlers added

packages/api/controllers/services/analyticsServiceAll.js, packages/api/controllers/services/analyticsServiceFilter.js, packages/api/controllers/webProperties/analyzeRepository.js, packages/api/controllers/webProperties/getSPAList.js, packages/api/controllers/webProperties/getWebPropertyList.js, packages/api/controllers/webProperties/gitOperations.js, packages/api/controllers/webPropertyServices/utils/getSearchResultForSPA.js
=> fix (api) : data issue resolved

packages/api/services/deployService.js
=> fix (api) : logs added for deploy service

packages/api/services/deployService.js
=> fix (api) : build path added

packages/api/controllers/application.js, packages/api/middlewares/authentication.js
=> fix (api) : invalid file issue resolved

packages/api/controllers/application.js
=> fix (api) : deployerror code added

packages/api/controllers/operatorServices/consumeEvent.js, packages/api/controllers/webPropertyServices/getLatestActivities.js, packages/api/routes/webProperty.js
=> feat : api fixes

packages/api/app.js, packages/api/controllers/scripts/eventDataDump.js, packages/api/controllers/scripts/eventTimeMatricesDump.js
=> feat (api) : data dump script added

packages/api/controllers/scripts/webPropertyDataDump.js
=> fix (api) : web property issue resolved

packages/api/controllers/operatorServices/saveAlias.js, packages/api/controllers/services/analyticsServiceFilter.js, packages/api/controllers/webPropertyServices/getCountByEnvWeeklyChart.js, packages/api/controllers/webPropertyServices/getLatestActivities.js, packages/api/controllers/webPropertyServices/utils/getTimeFrameForPropertyChart.js
=> fix (api) : fix services for api

packages/manager/components/chart/aggregate-chart.tsx, packages/manager/components/chart/deployment-week.tsx, packages/manager/components/chart/total-deployment.tsx, packages/manager/components/layout/sidebar/index.tsx, packages/manager/components/models/chart.ts, packages/manager/components/models/props.ts, packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/settings/manageSpa.tsx, packages/manager/components/web-property/activityStream.tsx, packages/manager/components/web-property/addProperty.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx, packages/manager/styles/globals.css, packages/manager/utils/api.utils.ts, packages/manager/utils/config.utils.ts, packages/manager/utils/endpoint.utils.ts
**Components Added:** 
- Chart Component :
1. Deployment Week
2. Total Deployment 
- Settings Component : 
1. API Key 
2. Delete Spa
3. Manage Spa
- Web-Property Component : 
1. Activity Stream
2. Spa Property
3. Web Property
- Utils:
1. API Request 
**Pages Added:**
1. Index Page (Route - /properties)
2. Web Property Page ( Route - /properties/{web-property-name} )
3. Spa Proeprty Page ( Route - /properties/{web-property-name}/spa/{spa-name} )
5. Web Property Settings Page ( Route - /properties/{web-property-name}/settings )
=> feat (manager) : components & pages added

packages/manager/Dockerfile, packages/manager/components/chart/aggregate-chart.tsx, packages/manager/components/chart/deployment-week.tsx, packages/manager/components/chart/total-deployment.tsx, packages/manager/components/layout/sidebar/index.tsx, packages/manager/components/models/chart.ts, packages/manager/components/models/props.ts, packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/settings/manageSpa.tsx, packages/manager/components/web-property/activityStream.tsx, packages/manager/components/web-property/addProperty.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx, packages/manager/styles/globals.css, packages/manager/utils/api.utils.ts, packages/manager/utils/config.utils.ts, packages/manager/utils/endpoint.utils.ts
=> feat(docker) : Dockerfile added for manager

packages/manager/Dockerfile, packages/manager/package.json
=> feat(docker) : Next build added in runtime

packages/manager/Dockerfile, packages/manager/components/models/props.ts, packages/manager/components/settings/manageSpa.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/package.json, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx
=> feat (manager) : Api call optimized

packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx
=> feat(prop): StaticProps changed to ServerSideProps

packages/manager/Dockerfile
=> feat(docker) : Root access added in docker

packages/manager/Dockerfile, packages/manager/components/web-property/activityStream.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json
- Added progress stepper from patternfly components and fixed height for the container div
- No
<details>
</details>
=> feat(activities) - Fix the Activity Stream Box Size and Changes in design of the list

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/settings/manageSpa.tsx, packages/manager/styles/globals.css
=> fix(settings) : Width adjusted for settings components

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/settings/manageSpa.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx
- Added Card and changed design for createAPI key and delete web property
- No
<details>
</details>
=> chore(1641) - Design Changes for API Key & Delete SPA

packages/api/services/deployService.js
=> fix(api) : env creation issue in operator

packages/manager/components/layout/index.tsx, packages/manager/components/web-property/activityStream.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/pages/api/auth/[...nextauth].tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx
- Added jwt token mechanism
- Fixed styles for cards
- No
<details>
</details>
=> fix(1637) & fix(1648) - Fix the Overlap of Body Content with Sidebar

packages/manager/pages/api/validate.tsx, packages/manager/pages/api/webPropertyOnboard.tsx, packages/manager/utils/endpoint.utils.ts
=> feat(property): Property onboarding api

packages/manager/components/models/props.ts, packages/manager/components/settings/apiKey.tsx, packages/manager/pages/api/auth/[...nextauth].tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx, packages/manager/utils/api.utils.ts
=> Fix/1637 - Fixed JWT token requests

packages/manager/components/models/props.ts, packages/manager/components/web-property/webProperty.tsx, packages/manager/pages/properties/index.tsx, packages/manager/utils/config.utils.ts, packages/manager/utils/endpoint.utils.ts
=> feat(property) : Property segregated, Property title added

packages/manager/components/auth/auth.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/envList.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/pages/api/validate.tsx, packages/manager/pages/api/webPropertyOnboard.tsx, packages/manager/pages/contact-us/index.tsx, packages/manager/pages/dashboard/index.tsx, packages/manager/pages/faqs/index.tsx, packages/manager/pages/feedback/index.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx, packages/manager/pages/properties/new.tsx, packages/manager/utils/api.utils.ts
=> feat(auth) : Validations & Authentication issue fixes for spaship manager

packages/manager/package.json, packages/manager/pages/api/validate.tsx, packages/manager/pages/api/webPropertyOnboard.tsx, packages/manager/utils/api.utils.ts, packages/manager/utils/logger.utils.ts
=> feat(logger) : Logger added in manager

packages/manager/components/chart/total-deployment.tsx, packages/manager/components/models/props.ts, packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/web-property/activityStream.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx
- Styled fixes for manger 
- No
<details>
</details>
=> Fix/settings-button - Style fixes for manger

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/utils/config.utils.ts
=> feat(notifications) : Notification time increased

packages/api/index.js, packages/api/middlewares/checkAccess.js
=> feat(api) : ldap checks removed

packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/envList.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx
- Resolves #1742 
- Changed url for getHost in envList (settings-page) and spaList page
- No
=> fix(1742) - Wrong URL is being shown on Settings Page

packages/manager/components/settings/envList.tsx, packages/manager/pages/properties/[propertyName]/index.tsx
=> hot-fix(regression-1742) - Changed application to applications in emptySPA page and settings page url

packages/manager/components/settings/createEnv.tsx
=> feat(env) : hostname field added env creation

packages/documentation/docs/qa-testing/test-process.md
Test(e2e):Updated the test document with cypress installation steps
No
<details>
</details>
=> Test(e2e):Updated the test document with cypress installation steps

packages/operator/src/main/java/io/spaship/operator/service/k8s/Operator.java
the Kubernetes client library fabric8.kubernetes.API was using the v1beta1 API for different purposes, the depreciation of v1beta1 API in a target k8s cluster raised a 404 error in the library, due to which the deployment engine failed to determine the routes.
Till the fabric8.kubernetes.API project fixes that bug a workaround is applied to fix this issue.
=> fix(operator) : workaround to fix KubernetesClientException

packages/manager/@types/spaProperty/index.d.ts, packages/manager/components/layout/header/index.tsx, packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/envList.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/pages/login/index.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/[propertyName]/spa/[spaName].tsx, packages/manager/pages/properties/index.tsx, packages/manager/utils/endpoint.utils.ts
- Resolves #1747 
- Minor UI fixes, Added table view for SPAList
- No
<details>
</details>
=> chore(1747) - SPAship UI enhancements for SPA List page and SPA details page

packages/manager/components/settings/apiKey.tsx, packages/manager/pages/api/validate.tsx
=> feat(apikey) : date picker added in apikey

packages/manager/components/settings/apiKey.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/pages/api/validate.tsx
=> fix(log) : log removed

packages/manager/components/settings/envList.tsx, packages/manager/package-lock.json, packages/manager/package.json
=> hot-fix(apikey-list) - version bump and spell check fix

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/pages/api/validate.tsx, packages/manager/pages/properties/[propertyName]/index.tsx
=> fix(manager) : apikey & env issues resolved 

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/pages/properties/[propertyName]/index.tsx
=> fix(manager) : env & domain issue fixed

packages/api/controllers/application.js, packages/api/controllers/operatorServices/operations/saveAlias.js, packages/api/models/alias.js, packages/api/models/application.js, packages/api/services/deployService.js
=> feat(api) : namespace added in services & changes in models

packages/api/package.json
[11.16 npm ERR! notarget No matching version found for @spaship/common@^1.3.0.](https://github.com/spaship/spaship/runs/6768918645?check_suite_focus=true#step:5:1971)
No
=> fix(api) : Spaship/common version issue resolved

packages/api/controllers/operatorServices/operations/getDeploymentRecordList.js, packages/api/package.json
=> fix(api) : Deployment record list issue resolved

packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/envList.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/pages/api/webPropertyOnboard.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/pages/properties/index.tsx
- Resolves #1776 
- Added status for API keys and added checkbox for new env type
- No
<details>
</details>
=> chore(1776) - Env form update and API key list enhancements

packages/manager/components/web-property/spaProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/pages/properties/index.tsx
- Resolves #1780 
-  Added debounce with search on SPA listing page and added search on properties list page
- No
<details>
</details>
=> chore(1780) - Search implementation in properties page and SPA list page

packages/api/controllers/application.js, packages/api/controllers/operatorServices/analytics/analyticsServiceAll.js, packages/api/controllers/operatorServices/analytics/analyticsServiceFilter.js, packages/api/controllers/operatorServices/analytics/utils/getLatestActivities.js, packages/api/controllers/operatorServices/event/consumeEvent.js, packages/api/controllers/operatorServices/operations/deletePropertyEnv.js, packages/api/models/activityStream.js, packages/api/models/application.js, packages/api/models/event.js, packages/api/routes/webProperty.js
1. Changes in Events
2. Deletion of env
3. Openshift base url
<details>
</details>
=> feat(api) : Deletion of env & hosted url of a property added

packages/api/controllers/operatorServices/operations/getPropertyList.js
=> fix(api) : access url added into the list

packages/api/controllers/operatorServices/operations/envCreation.js, packages/api/controllers/operatorServices/operations/saveAlias.js
=> feat(api): aggressive env creation in operator

packages/api/config.js, packages/api/db.js
=> fix(api) : mongo cred issue resolved

packages/api/db.js
=> fix(api) : mongoose options added

packages/manager/components/web-property/spaProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json
- Resolves #1787 
- Added Access url for SPAs
- No
<details>
<summary>
Access url with no data
</summary>
</details>
=> chore(1787) - Create Openshift Hosted path Hyperlink

packages/cli/src/common/zip.js
=> fix(cli) : zipping file issue resolved

packages/api/controllers/operatorServices/event/consumeEvent.js
=> fix(api) : accesurl issue for basepath resovled

packages/cli/README.md
=> feat(cli) : spaship env descriptions added

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/package.json
Changes in Readme
<details>
</details>
=>  feat(cli) : changes in readme

packages/manager/components/web-property/spaProperty.tsx
- Changed internal url trailing slash
- No
=> chore(1808) - Add trailing forward-slash / for the frontend

packages/api/controllers/application.js, packages/api/controllers/operatorServices/event/consumeEvent.js, packages/api/services/deployService.js
=> fix(api) : rootspa issue resolved

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js
=> hotfix(cli) : baremetal issue resolved

packages/api/controllers/apiKey.js, packages/api/routes/apiKeys.js
Subject: feat(api) : apikey deletion service updated
Developer : @soumyadip007 
<details>
</details>
=> feat(api) : apikey deletion service updated

packages/api/middlewares/authentication.js
- Fixes (error code issue) 
- 401 error code issue resolved for authorization 
- No
<details>
</details>
=> fix(api) : response status code changed for auth

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js
- Fixes (error handling, refactor in error message)
- File not found error handled 
- Error messages refactored and mapped for particular error code
- No
=> fix(cli): CLI error handling & changes error message

packages/api/controllers/apiKey.js, packages/api/controllers/application.js, packages/api/models/apiKey.js
- APIkey Separation for envs 
- API key creation for envs
- Changes in Create API key & API key list response
- Changes in API key model
- No
=> feat(api) : API key segregation of envs

packages/api/config.js, packages/api/middlewares/authentication.js
- Segregate Env for the API keys (deployment)
- Segregate env for API key
- DB URL changes for local run
- No
=> fix(api) : env checks added for the api-key during deployment

packages/api/middlewares/authentication.js
- loggers added for request
- Check Request Body & Headers
- Error message printing
- No
=> fix(api) : loggers added for request

packages/api/controllers/apiKey.js, packages/api/controllers/application.js, packages/api/index.js, packages/api/middlewares/authentication.js, packages/api/models/apiKey.js, packages/api/routes/apiKeys.js
- New Checks added for API keys (env checks)
- Changes in API Key list 
- NODE_TLS_REJECT_UNAUTHORIZED added for local connection
- Changes APIKey model & service
- Validation added for Create API Key Payload
- Changes in API Key list response
- Checking added for env in API Key (one key for multiple envs)
- NODE_TLS_REJECT_UNAUTHORIZED set to zero (fix)
- No
=> feat(api) : check env feature added in API key

packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/envList.tsx, packages/manager/package.json, packages/manager/pages/api/validate.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx
- Env & Label added into API Key
- Datepicker issue resolved
- Label added into API Key list 
- Env Selection added into API key (single key on multiple events)
- Label added for API Key (Auto-generated)
- Datepicker forward month issue resolved
- Upper range added for Date (365 days)
- Patternfly/react-core package updated into 4.221.11
- Changes in validate api (new fields added into payload)
- No
=> feat(manager) : API Key revamped 

packages/manager/components/settings/apiKey.tsx
- Environment & label issues resolved
- Validation added for Label (35 char limit, special-char restriction)
- Error message added for the invalid label
- Style fixed for Create button (spacing added)
- Button expand issue for invalid datepicker resolved
- No
=> fix(api) : env & label issues resovled

packages/operator/src/main/java/io/spaship/operator/service/k8s/Operator.java, packages/operator/src/main/resources/application.properties, packages/operator/src/main/resources/openshift/environment-template.yaml
Added support for the router, which is going to be a part of every environment 
No.
=> feat(operator) : added support for internal router

packages/api/controllers/apiKey.js
- Created by field added into the response
- No
=> fix(api) : created by added in response

packages/api/app.js, packages/api/controllers/application.js, packages/api/routes/applications.js
- Rate limiter added for public APIs
- Deploy APIs configured
- Rate limiter added for all the public apis (300 requests per min -> 5 req per sec)
- Delete applications by property name api configured
- No
=> feat(api) : Delete API & Rate limiter configured  

packages/manager/components/layout/header/index.tsx, packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/deleteSpa.tsx, packages/manager/components/settings/envList.tsx, packages/manager/components/settings/manageSpa.tsx, packages/manager/components/web-property/newProperty.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/components/web-property/webProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/pages/_app.tsx, packages/manager/pages/api/webPropertyOnboard.tsx, packages/manager/pages/index.tsx, packages/manager/pages/properties/[propertyName]/index.tsx, packages/manager/pages/properties/[propertyName]/settings/index.tsx, packages/manager/scripts/GlobalConstants.ts, packages/manager/styles/globals.css, packages/manager/utils/api.utils.ts
- Resolves #1821 
- Added banner as info
- No
<details>
</details>
=> chore(1821) - Add feedback button and another minor changes

packages/manager/components/settings/createEnv.tsx
- Handled no env creation issue 
- No Env created issue handled 
- Alert added for the no env creation
- Remove data once the modal is closed
<details>
</details>
- No
=> fix(manager) :  handled no env created issue

packages/api/controllers/scripts/apiKeysDump.js, packages/api/routes/scripts/dataDump.js
- Script added for API Keys endpoint
- Scripts for API Key needed for Key Migration
- No
=> feat(api) : scipt for apikeys

packages/manager/components/settings/createEnv.tsx, packages/manager/components/web-property/newProperty.tsx
- Change in Error Message
- "Unable to process the request, Please try again if this ...." message added as per the discussion with @arkaprovob & @mudit94 
- No
=> fix(manager) : Error message changed

packages/manager/components/layout/header/index.tsx, packages/manager/components/settings/apiKey.tsx, packages/manager/components/settings/createEnv.tsx, packages/manager/components/settings/envList.tsx, packages/manager/components/web-property/spaProperty.tsx, packages/manager/package-lock.json, packages/manager/package.json
- Resolves #1842 
- Changed 
- No
<details>
</details>
=> Chore/1842 - Add feedback button

package.json, packages/manager/package.json
- spaship monoerpo version changed to 22.08.0
- spaship manager version changed to 1.4.0
- No
=> feat(spaship) : spaship version changed

packages/manager/components/web-property/spaProperty.tsx
- Path mismatch with SPA name issue resolved 
- No
<details>
</details>
=> fix(manager) : path mismatch with spa issue

packages/api/controllers/application.js, packages/api/controllers/operatorServices/event/consumeEvent.js, packages/api/controllers/operatorServices/operations/getPropertyList.js, packages/api/controllers/operatorServices/operations/saveActivity.js, packages/api/controllers/operatorServices/operations/saveAlias.js, packages/api/models/activityStream.js, packages/api/models/application.js
- Identifier added for spa props
- Activity Stream configured
- NextRef added for spa versioning
- Identifier added into application collection 
- SPA listing response changed (identifier added)
- Identifier added to Consume Events config (operator based on identifier)
- Changes in Activity stream collection (id removed)
- Activity stream for creating a new property, creating new env, creating API key, uploading spa
- No
=> feat(api) : activity stream, nextRef & indentifier configured into orchestrator

packages/manager/@types/spaProperty/index.d.ts, packages/manager/components/web-property/spaProperty.tsx
- Identifier added for spa props
- Access URL checks added
- Identifier added into spa props
- Group properties by identifier
- Call spa page by identifier
- Validations added for access url (without access url property will not be listed)
- No
=> feat(manager) : Identifier added for spa props

packages/api/controllers/scripts/applicationDataDump.js, packages/api/controllers/scripts/eventDataDump.js
- Changes in data script
- Changes in application and event data script
- createdAt & updatedAt will be added from the payload
- No
=> fix(api) : changes in data script for applications & events

packages/operator/pom.xml, packages/operator/src/main/java/io/spaship/operator/service/k8s/SideCarOperations.java, packages/operator/src/main/resources/META-INF/resources/index.html, packages/operator/src/main/resources/openshift/environment-template.yaml
Nested directory SPA upload bug
When re-deployed to a path, it took over all the subpaths. As a result, those get deleted if there are other nested spa directories.
This patch aims to fix that issue.
Yes,  there is a change in the case of a nested directory structure. The operator will replace / this char of mapping attribute  with _ to create unique directories for independent create, delete, update operation
=> fix(operator) : nested directory overriding issue on updating the ent directory. SPASHIP-982

packages/manager/.dockerignore
1. Added dockerignore 
No
<details>
</details>
=> chore: added docker ignore file

packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
- Identifier added for SPA listing
- Identifier added into the group by query for SPA listing
- Identifier added for the SPADetails page query
- No
=> fix(manager) : Identifer added into listing

packages/api/controllers/application.js, packages/api/openapi.yml
- Swagger Doc Updated
- Swagger Doc updated for the APIs
- No
<details>
</details>
=> feat(api) : swagger doc updated

packages/manager/src/context/AuthGuard/AuthGuard.tsx, packages/manager/src/layouts/AppLayout/components/Nav/Nav.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/pages/_app.tsx, packages/manager/src/pages/coming-soon.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/AddWebPropertyPage/AddWebProperty.utils.ts, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/StayTunedPage/StayTunedPage.tsx, packages/manager/src/views/StayTunedPage/index.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateAPIKeyForm/CreateAPIKeyForm.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateEnvForm/CreateEnvForm.tsx, packages/manager/src/views/WebPropertyListPage/components/WebPropertyCard/WebPropertyCard.tsx
1. Added length validation for fields
2. Applied label to field names
3. Responsive charts
4. Clickable links in table
5. Added search in spa property list page
No
<details>
</details>
=> fix(manager): added validation and responsive chart

packages/api/controllers/apiKey.js, packages/api/controllers/application.js, packages/api/models/apiKey.js
- Env added for apikeys (will be consumed from FE)
- Env added into apikey model
- Env into apikey response
- Save env into database
- No
<details>
</details>
=> feat(api) : env added for apikeys

packages/manager/Dockerfile, packages/manager/package-lock.json
1. Added lockfile back
2. Added arg inside docker file
No
<details>
</details>
=> Added missing lockfile for manager

packages/manager/package-lock.json
Fixed corrupt lockfile
No
<details>
</details>
=> fix(manager): fixed corrupted lockfile

.github/workflows/manager-ci.yaml
GitHub action for the manager is updated as per build requirements.
Only change in manager-build action
No
=> Github action update for SPAship manager

.github/workflows/manager-ci.yaml
GitHub action for the manager is updated as per build requirements.
Only change in manager-build action
No
=> Change in GitHub action, manager build CI

packages/manager/src/views/AddWebPropertyPage/AddWebProperty.utils.ts, packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateEnvForm/CreateEnvForm.tsx
1. Fixed typo in environment
2. Change env table to borderless
No
<details>
</details>
=> Fixed typo and removed lines in tables

packages/api/controllers/application.js, packages/api/controllers/operatorServices/operations/deletePropertyEnv.js, packages/api/controllers/operatorServices/operations/saveActivity.js, packages/api/middlewares/authentication.js, packages/api/models/activityStream.js
- Logger added for authentication
- Payload added into activity stream
- Payload added for all the delete activites
- Logger added for authentication
- No
<details>
</details>
=> feat(api) : payload for the activities & logger added

packages/api/controllers/operatorServices/event/consumeEvent.js, packages/api/controllers/operatorServices/operations/saveActivity.js, packages/api/controllers/operatorServices/operations/saveAlias.js, packages/api/models/activityStream.js
- Payload issues resolved for saving property
- NextRef warning issues resolved
- No
<details>
</details>
=> fix(api) : payload issues resolved

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateEnvForm/CreateEnvForm.tsx
1. Showing prod or pre prod for env type label
No
<details>
</details>
=> feat(prod-label): changed slider in env to dynamic

packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
- Added routing fallback for non-exsitsing SPAS and web-props
=> chore(spaship(manager)) - Random property name URL bug

packages/operator/src/main/resources/openshift/environment-template.yaml
Environment resource config file with the latest sidecar version.
=> chore(operator): updated the sidecar version in env template manifest file

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/Radio/Radio.tsx, packages/manager/src/components/Radio/index.tsx, packages/manager/src/components/Radio/radio.module.css, packages/manager/src/components/index.tsx, packages/manager/src/layouts/AppLayout/components/Nav/Nav.tsx, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/AddWebPropertyPage/AddWebProperty.utils.ts, packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateEnvForm/CreateEnvForm.tsx
1. 1015
2. 1024
1. Fixed pointer cursor in profile icon in navbar
2. Added new radio button for env pages
3. Fixed invalid redirect on property page
No
<details>
</details>
=> Added pointer cursor on hover in profile and new radio button

packages/api/controllers/operatorServices/operations/deletePropertyEnv.js, packages/api/controllers/operatorServices/operations/ephemeralEnvDeletion.js, packages/api/utils/agenda-jobs/initializeDeleteJobs.js
- Validation added for eph deletion
<details>
</details>
=> fix(api): validations added in deletion for eph

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/apiKeys/queries.tsx, packages/manager/src/services/ephemeral/index.tsx, packages/manager/src/services/ephemeral/queries.tsx, packages/manager/src/services/ephemeral/types.ts, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/services/webProperty/queries.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/index.tsx
=> Spaship/944 fix - Ephemeral preview frontend

packages/api/controllers/operatorServices/operations/getEphList.js
-- ActionId in Response issue resolved 
<details>
</details>
=> fix(api) : actionId response issue resolved

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
- Fixes - Broken date format in activity stream
- No
<details>
</details>
=> manager(activity-stream) - Fixed date time for activity stream

packages/cli/package.json, packages/cli/src/commands/deploy.js
- Eph argument added
- Features are testing in the Dev CLI
- -preview, -P and --prid added
<details>
</details>
=> feat(cli) : ephemeral env changes added

packages/api/config.js, packages/api/controllers/operatorServices/operations/ephemeralEnvDeletion.js
-  Typecast issue resolved
<details>
</details>
=> fix(api) : typecast issue in date resolved

.github/workflows/manager-ci.yaml, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/config/env.ts, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
- Added fixes for invalid time and intro video arg
- No
=> Chore(manager) - Added fixes for invalid time and intro video arg

packages/manager/src/layouts/AppLayout/AppLayout.tsx
- Added patternfly react banner for eph preview doc
- No
<details>
</details>
=> manager(banner) - Added banner for eph preview doc

packages/api/.eslintrc.json, packages/api/src/main.ts, packages/api/src/repository/mongo/model/event-time-trace.model.ts, packages/api/src/repository/mongo/model/event.model.ts, packages/api/src/server/api-key/service/apikey.service.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/property/service/property.factory.ts, packages/api/src/server/sse-services/event-time-trace.entity.ts, packages/api/src/server/sse-services/event.entity.ts, packages/api/src/server/sse-services/service/sse-consume.module.ts, packages/api/src/server/sse-services/service/sse-consume.service.ts
1. Event & EventTimeTrace entities refactored
2. Event Processing Added
3. AccessURL, Ref acknowledgement added
4. Time to Deploy processing 
<details>
</details>
=> feat(api) : event processing & sse added

packages/api/package-lock.json, packages/api/package.json, packages/api/src/app.module.ts, packages/api/src/configuration/index.ts, packages/api/src/main.ts, packages/api/src/server/agenda/agenda.module.ts, packages/api/src/server/agenda/agenda.service.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.module.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/environment/service/environment.factory.ts, packages/api/src/server/environment/service/environment.module.ts, packages/api/src/server/environment/service/environment.service.ts, packages/api/src/server/property/service/property.module.ts, packages/api/src/server/property/service/property.service.ts
1. Agenda added into API
2. Agenda Jobs defied for deleting eph env
3. Ephemeral Preview Feature added
4. Ephemeral Deployment & Processing
5. Delete Env feature added (validations added for only ephemeral)
6. CORS enabled
<details>
</details>
=> feat(api) : ephemeral preview added

packages/api/.eslintrc.json, packages/api/package-lock.json, packages/api/package.json, packages/api/src/configuration/index.ts, packages/api/src/configuration/pipe/trim-pipe.pipe.ts, packages/api/src/server/agenda/agenda.service.ts, packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/analytics/service/analytics.factory.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/api-key/service/apikey.factory.ts, packages/api/src/server/api-key/service/apikey.service.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/auth/auth.guard.ts, packages/api/src/server/environment/service/environment.factory.ts, packages/api/src/server/environment/service/environment.service.ts, packages/api/src/server/event/service/event.service.ts
Subject:  feat(api) : event stream producer added 
1. Lint issues resolved
2. Changes in activity stream api (applicationIdentifier added)
3. Changes in ephemeral environment apis (return applications with the ephemeral envs)
NO
<details>
</details>
=> feat(api) : changes in event and activity apis

packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/api-key/apikey.dto.ts, packages/api/src/server/api-key/service/apikey.service.ts
Subject:  feat(api) : filtering added for the realtime events
1.  Filtering added for the realtime events
2. Event channels created for the specific properties
3. Changes in API Key response
NO
<details>
</details>
=> feat(api) : filtering added for the realtime events

packages/api/src/configuration/index.ts, packages/api/src/repository/mongo/model/activity-stream.model.ts, packages/api/src/repository/mongo/model/apikey.model.ts, packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/server/api-key/apikey.dto.ts, packages/api/src/server/api-key/apikey.entity.ts, packages/api/src/server/api-key/service/apikey.factory.ts, packages/api/src/server/api-key/service/apikey.service.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/auth/auth.guard.ts
Subject: feat(api) : api-key authentication added for deployment & event apis
1. ExpirationDate added for APIKey Model (expiredDate removed)
2. APIKey validations added for deployment and event apis
3. CreatedBy added for Deployment
NO
<details>
</details>
=> feat(api) : api-key authentication added for deployment & event apis

packages/api/src/repository/generic-repository.abstract.ts, packages/api/src/repository/mongo/mongo-generic-repository.ts, packages/api/src/server/analytics/service/analytics.service.ts
feat(api) : changes in activity stream response
1.  GetByAnyAndSorted function added
2. Activity stream response changed 
NO
<details>
</details>
=> feat(api) : changes in activity stream response

packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/environment/environment.dto.ts, packages/api/src/server/environment/service/environment.service.ts
Subject: fix(api) : changes in sync api
1.  Changes in Sync API Request
2. PropertyIdentifier and Env added into payload
NO
<details>
</details>
=> fix(api) : changes in sync api

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/components/ActivityStream/index.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/analytics/types.ts, packages/manager/src/services/persistent/queries.tsx, packages/manager/src/services/sync/index.tsx, packages/manager/src/services/sync/queries.tsx, packages/manager/src/services/sync/types.ts, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/index.tsx
- Adding sync service
- Update for activity stream
- No
<details>
</details>
=> chore(sync-service) - Add sync service feature

packages/manager/src/components/ActivityStream/ActivityStream.tsx
- Added env_sync activity
- No
=> Fix/activity stream - Added env_sync activity

packages/api/src/server/application/application.controller.ts
Subject:  fix(api) : change in applications api
1.  change in application endpoint
NO
<details>
</details>
=> fix(api) : change in applications api

packages/manager/src/services/analytics/queries.tsx
=> Fix/spa activity - Fixed fetch request

packages/api/src/configuration/index.ts
1. Whitelisting apis
<details>
</details>
=> fix(api) : auth whitelisting added

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.dto.ts
1. path validation issue
2. Limit set to 1
<details>
</details>
=> fix(api) : path validation issue

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/event/service/event.service.ts
Subject:  fix(api) : undefined ref issue resolved
1. Undefined ref issue resolved
NO
<details>
</details>
=> fix(api) : undefined ref issue resolved

packages/api/src/repository/generic-repository.abstract.ts, packages/api/src/repository/mongo/mongo-generic-repository.ts, packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/event/service/event.service.ts
Subject:  feat(api) : pagination added for activity stream
1.  Pagination added for Activity stream
2. Default skip set to 0 and limit set to 100
NO
<details>
</details>
=> feat(api) : pagination added for activity stream

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/ephemeral/queries.tsx
- Added extra events and infite scroll to the activity stream
- No
<details>
</details>
=> chore(activity-stream) - Added extra events to the activity stream

packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/ephemeral/types.ts, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
=> chore(sync-activity) - Added createdBy to eph

packages/manager/src/context/AuthGuard/AuthGuard.tsx, packages/manager/src/types/next-auth.d.ts
- Added extra type in session 
- No
=> fix(session-type) - Added error type for session

packages/manager/src/services/persistent/types.ts, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx
- A way update sync config
- No
<details>
</details>
=> chore(update-sync-config) - Added sync config values

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx
- Fixed error for form
- Added info icon
- No
<details>
</details>
=> chore(sync-info) - Fixed sync error and added info icon

packages/api/src/server/application/application.controller.ts
Subject: fix(api) : more zip types added
<details>
</details>
=> fix(api) : zip types added for bz, 7z

packages/api/src/server/application/application.dto.ts
fix(api) : validation removed for ref
1. Validation removed for ref
<details>
</details>
=> fix(api) : validation removed for ref

packages/api/src/server/application/application.controller.ts
fix(api) : zip type issue
<details>
</details>
=> fix(api) : zip type issue

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : validation message refactored
1.  Validations message refactored for the Application Deploy response
2. CLI will show these message in Error (rather than generic error)
3. Identifier added for activity stream
NO
<details>
</details>
=> feat(api) : validation message refactored

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) ; deployed by & trailing slash issue
1.  Deployed by removed from the Response
2. Trailing slash removed
NO
<details>
</details>
=> fix(api) ; deployed by & trailing slash issue

packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/service/application.service.ts
Subject: feat(api) : application Identifier added in endpoint
1.  It will return the envs based on particular implementations
2. It will be integrated into SPA details page
NO
<details>
</details>
=> feat(api) : applicationIdentifer added in endpoint

packages/api/src/server/analytics/service/analytics.service.ts
Subject:  fix(api) : remove empty incoming req for stream
1.  empty response from FE for applicationIdentifier can break the activity stream in future
3. fix added
NO
<details>
</details>
=> fix(api) : remove empty incoming req for stream

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : generate access url for response
1.  Generated Access URL
2. Validation removed
NO
<details>
</details>
=> feat(api) : generate access url for response

packages/api/src/server/application/service/application.factory.ts
Subject: feat(api) : npm pack support added
NO
<details>
</details>
=> feat(api) : npm pack support added

packages/api/src/configuration/index.ts, packages/api/src/server/application/service/application.factory.ts
Subject:  fix(api) : deployment response message changed
1. Access URL message changed
2. Invalid path message changed
NO
<details>
</details>
=> fix(api) : deployment response message changed

packages/api/src/server/application/service/application.factory.ts
Subject:  fix(api) : version issue resolved
1. Version issue resolved
2. Nested path generation issue resolved
NO
<details>
</details>
=> fix(api) : version issue resolved

packages/api/src/server/application/service/application.factory.ts
Subject:  feat(api) : ref issue resolved for the deployment
1.  Trim the limit to 60 while sending the request to operator (else everything will be same, no restriction on length)
2. No validations added for that
NO
<details>
</details>
=> feat(api) : ref issue resolved for the deployment

packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/links.ts, packages/manager/src/pages/dashboard.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/DashboardPage/components/ActivityStream/index.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/DashboardPage/components/Analytics/index.tsx, packages/manager/src/views/DashboardPage/index.tsx
dasboard boilerplate
<details>
</details>
=> feat(manager): dashboard boiler plate

packages/api/src/server/analytics/deployment-time-response.dto.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : find on multiple environments
1.  Find applications for multiple environments 
2. Accuracy in the Average deployment time
3. 0.23 sec gap resolved
NO
<details>
</details>
=> feat(api) : find on multiple environments

packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/analytics/deployment-count-response.dto.ts, packages/api/src/server/analytics/service/analytics.factory.ts, packages/api/src/server/analytics/service/analytics.service.ts
Subject:  feat(api) : ephemeral grouping added for analytics
1.  Ephemeral Environment grouped in the analytics response
2. Response mapped added for deployment apis
3. Swagger modified
NO
<details>
</details>
=> feat(api) : ephemeral grouping added for analytics

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/commands/init.js, packages/cli/src/services/deployService.js
1.  error message changed for the CLI
NO
<details>
</details>
=> feat(api) : error message changed for the CLI

package-lock.json, package.json, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/commands/init.js, packages/cli/src/services/deployService.js, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/views/DashboardPage/components/ActivityStreamDashboard/ActivityStreamDashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
Implementing Activity Stream of Spa-ship Dashboard (Only Application deployed to be shown for dashboard activity Stream)
No
[screen-capture (6).webm](https://user-images.githubusercontent.com/56580582/211544121-ddd20865-8125-4638-98bc-de3d11748f07.webm)
=> Implementing Activity Stream of Dashboard

packages/manager/package-lock.json, packages/manager/src/services/analytics/index.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/ActivityStreamDashboard/ActivityStreamDashboard.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Implemented analytics section of the SPAship dashboard
No
<details>
</details>
=> Develop dashboard analytics

packages/api/src/configuration/index.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/api-key/apikey.controller.ts, packages/api/src/server/api-key/service/apikey.service.ts, packages/api/src/server/auth/auth.guard.ts, packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/permission/service/permission.service.ts, packages/api/src/server/property/property.dto.ts, packages/api/src/server/property/service/property.service.ts, packages/api/src/server/sot/rover/rover.controller.ts, packages/api/src/server/sot/rover/service/rover.service.ts, packages/api/src/server/webhook/service/webhook.controller.ts
1. API Key and Env Delete endpoint refactored
2. Name added Initial Property Creation
3. Code Formatted 
NO
<details>
</details>
=> fix(api) : endpoint mismatch & name store in initial permission for Property Creation

packages/manager/src/services/analytics/index.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/ActivityStreamDashboard/ActivityStreamDashboard.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx
SPASHIP-1119
Refactored the analytics cards section to show additional data. Minor tweaks in the dashboard graph and making all the headings bold. 
No 
<details>
</details>
=> fix(manager): fix dashboard analytics card

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/DashboardPage/components/ActivityStreamDashboard/ActivityStreamDashboard.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
=> Lint errors fixed

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/services/analytics/types.ts, packages/manager/src/views/DashboardPage/components/ActivityStreamDashboard/ActivityStreamDashboard.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
Made consistent design across dashboard page
=> Design Consistent across dashboard Page

packages/api/src/server/analytics/service/analytics.service.ts
Subject:  fix(api) : error handling added for webhook
1.  Error handling added for webhook
NO
<details>
</details>
=> fix(api) : error handling added for webhook

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/EmptyInfo/EmptyInfo.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx
1) Allows users to copy the initial steps for empty web property.
2) URL validation on Publish domain on web property details page and env page.
No
<details>
1) Allows users to copy the initial steps for empty web property.
2) URL Validation on web property details page
3) URL Validation on create env page
</details>
=> fix(manager): Adding steps copy feature on empty web property, URL Validation on publish domain URL 

packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
Skip and Limit eliminated as no pagination applied, spelling corrected
[screen-capture (15).webm](https://user-images.githubusercontent.com/56580582/213449630-dfb3f99a-00a3-4dee-888a-a5ccaf7ae569.webm)
=> Removed skip and limit

packages/api/src/server/analytics/service/analytics.factory.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/api-key/service/apikey.service.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/environment/service/environment.service.ts, packages/api/src/server/event/service/event.service.ts, packages/api/src/server/webhook/service/webhook.service.ts, packages/api/src/server/webhook/webhook-response.dto.ts
Subject:  feat(api) : Webhook response refactored
1.  Webhook response refactored (specific response on APIKey, Application properties)
3. Source issue resolved in Activity stream (consistent  for webhook)
4. Activity stream converted to Webhook Response
NO
<details>
</details>
=> feat(api) : webhook response refactored

packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/event/service/event.service.ts, packages/api/src/server/permission/permission.controller.ts, packages/api/src/server/permission/permission.dto.ts, packages/api/src/server/permission/service/permission.factory.ts, packages/api/src/server/permission/service/permission.service.ts
Subject:  feat(api) : changes in permission module
1. Changes in Create Permission Request Modules (changes in activity stream)
2. Changes in Get permission by Action
3. Lint issues resolved and Code formatted
NO
<details>
</details>
=> feat(api) : changes in permission module

packages/api/src/server/analytics/service/analytics.service.ts
Subject:  provide initial access issue for webhook
1. provide initial access issue for webhook
NO
<details>
</details>
=> fix(api): provide initial access issue for webhook

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
Table skeleton is loading on page refresh, new filter value.
<details>
</details>
=> fix(manager): Table skeleton loading on filter value change and page refresh

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Syncing the legend data color with color of Chart lines.
No 
<details>
</details>
=> Fix dashboard graph color

packages/api/src/server/api-key/apikey.controller.ts, packages/api/src/server/api-key/apikey.dto.ts, packages/api/src/server/api-key/service/apikey.module.ts, packages/api/src/server/api-key/service/apikey.service.ts
Subject:  chore(api) : Changes in Delete API Key service
1. Changes in delete API Key endpoint
2. DeleteAPIKey DTO added
3. Changes in Delete API Key Service
NO
<details>
</details>
=> chore(api) : Changes in Delete API Key service

packages/api/src/server/permission/service/permission.factory.ts
Subject:  chore(api): name added in permission response
1.  Name added into Grouped Permission Response
NO
<details>
</details>
=> chore(api): name added in permission response

packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
SPASHIP-1119
Added time format in spaship dashboard Average deployment time card
No 
<details>
</details>
=> fix(manager): update the time format in spaship dashboad analytics

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/services/apiKeys/queries.tsx, packages/manager/src/services/apiKeys/types.ts, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx
Change in Delete API Key Endpoint for RBAC
NO
=> chore(manager) : changes in apikey deletion endpoint

packages/api/src/server/auth/auth.guard.ts, packages/api/src/server/permission/permission.dto.ts, packages/api/src/server/permission/service/permission.factory.ts, packages/api/src/server/permission/service/permission.service.ts
Subject:  few validations & rules added for RBAC
1.  Validations added for Permission creation & Deletions request
2. Separate  DTO added for Delete permissions (specific validations)
3. Changes in Permission Creation Response (Send only created permission in the Response)
4. Rules added for Self Deletion (Requester cannot delete his/her access for Permission Creation & Deletion, if he/she has that access, else it might get into deadlock)
5. Email & basic validations added
NO
<details>
</details>
=> fix(api) : few validations & rules added for rbac

packages/api/src/server/permission/service/permission.factory.ts
Subject: chore(api) : changes in group permission response
1.  Changes in group api response 
2.  Response change requirement from the FE
NO
<details>
</details>
=> chore(api) : changes in group permission response

packages/api/package-lock.json, packages/api/package.json
Subject:  feat(api) : version bump
1. Orchestrator Version bumping to 3.1.0
NO
<details>
</details>
=> feat(api) : version bump

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/Banner/Banner.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/links.ts, packages/manager/src/pages/document.tsx, packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/DocumentsPage/components/DocumentCard/DocumentCard.tsx, packages/manager/src/views/DocumentsPage/components/DocumentCard/index.tsx, packages/manager/src/views/DocumentsPage/index.tsx
Consolidating all the documents of SPAship at a single place
No
=> feat(manager) : Consolidating Documents

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
=> fix(manager) : build issue resolved for Search value input changed

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
=> fix(manager) : ptternfly version fix

packages/api/src/main.ts, packages/api/src/server/permission/service/permission.factory.ts, packages/api/src/server/sot/rover/service/rover.factory.ts
Subject:  chore(api) : formatted, version updated & rover api optimized 
1. UID removed from the rover call
2. Swagger Version Updated
3. Code formatted and linted 
NO
<details>
</details>
=> chore(api) : formatted, version updated & rover api optimized 

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/utils/toPascalConvert.ts, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/AddMembers.tsx, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/ConfigureAccess.tsx, packages/manager/src/views/WebPropertyEnvPage/components/EditAccess/EditMemberAccess.tsx
=> fixing pascal case, delete button disable for user

packages/api/src/server/permission/service/permission.service.ts
Subject:  chore(api) : default sort by name for Permission list
1.  Default sort added for email for the Permissions list 
NO
<details>
</details>
=> chore(api) : default sort by email for Permission list

packages/manager/src/services/rbac/queries.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/AddMembers.tsx, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/ConfigureAccess.tsx, packages/manager/src/views/WebPropertyEnvPage/components/EditAccess/EditMemberAccess.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx
=> feat(manager) : Bug fixing toasters and add members validations

packages/manager/src/views/DocumentsPage/DocumentsPage.tsx
Corrected Spelling for Real Time
=> fix(Manager): Spelling corrected in documents page

packages/api/src/server/permission/service/permission.service.ts
Subject:  fix(api) : default limit increased for permission api
1.  default limit increased for permission api
NO
<details>
</details>
=> fix(api) : default limit increased for permission api

packages/api/src/server/sot/rover/rover.controller.ts, packages/api/src/server/sot/rover/service/rover.factory.ts, packages/api/src/server/sot/rover/service/rover.service.ts
Subject:  chore(api) : search the rover group list
1.  Search the List of the Rover Group
2. Query param added into the Existing API
NO
<details>
</details>
=> chore(api) : search the rover group list

packages/api/src/server/property/service/property.service.ts
Subject:  feat(api) : envs added in the all property details api
1. Envs added into the all property API response 
NO
<details>
</details>
=> feat(api) : envs details added in the all property api

packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/repository/mongo/model/auth-action-lookup.model.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/event/service/event.service.ts
Subject:  feat(api) : SSR support added for the SPAship 
1. Changes in the Existing Collection for the Applications
2. New attributes in Entity and DTO added for the SSR
3. Integration of SSR in the existing Deployment API
4. Services added for SSR Operations
5. SSR application search filter added
6. Config SSR endpoint added
NO
<details>
</details>
=> feat(api) : SSR support added for SPAship 

packages/api/src/server/application/application.controller.ts, packages/api/src/server/property/service/property.service.ts, packages/api/src/server/role/service/role.service.ts, packages/api/src/server/sot/rover/rover.controller.ts, packages/api/src/server/sot/rover/service/rover.factory.ts, packages/api/src/server/sot/rover/service/rover.service.ts
Subject: chore(api) : code formatted & quarries added
1.  Core formatted after the prettier version updating
2.  Roll back to queries for the created by in deployment api
NO
<details>
</details>
=> chore(api) : code formatted & quarries added

packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx
Added link to web property page  from Total Deployment and Total Properties in Dashboard 
No
[screen-capture (21).webm](https://user-images.githubusercontent.com/56580582/219029121-fce1e2c6-ab2c-421a-bd13-0ffa83fb7a5e.webm)
=> fix(Manager): Link to web property page

packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : SSR Config service and version update
1. Update the SSR config in the operator
2. Don't update the SSR config if the Application is not preset
3. Validation added for the SSR Config Request
4. Version attribute added the Application schema for the internal use
5. Increment the version for each deployment 
NO
<details>
</details>
=> feat(api) : SSR Config service and version update

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : ImageUrl for SSR validation resolved 
1.  Validations added for the imageUrl
2. Source of the Image check added
3. Image validations added for the Image URL
4. Default healthCheck path mapped with the path
**Validations Format for the ImageUrl :** 
Allowed Image Format :
- spaship
- spaship:latest
- spaship-image:latest
- spaship-registry.com/spaship-image:1.0.0
- spaship_org/spaship_image:1.2.3-beluga
Not Allowed Image Format :
- SPAship (uppercase letters not allowed)
- SPAship_image@sha256:abc123 (invalid character @)
- spaship/image (slashes not allowed in repository name)
- spaship-image: (tag or digest cannot be empty)
NO
<details>
</details>
=> feat(api) : Image Registry URL validation for SSR added 

packages/api/src/configuration/index.ts, packages/api/src/server/application/service/application.service.ts
1. Read imageUrl regex from the env
2. Error log message changed
NO
<details>
</details>
=> chore(api) : ssr imageurl validations refactored

packages/api/.eslintrc.json, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : validations for config resolved
1.  Env and Application validation added for Config Update
2. Regex lint issue resolved 
NO
<details>
</details>
=> fix(api) : validations for config resolved

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/links.ts, packages/manager/src/pages/sla.tsx, packages/manager/src/services/rbac/index.tsx, packages/manager/src/services/rbac/queries.tsx, packages/manager/src/services/rbac/types.ts, packages/manager/src/styles/globals.css, packages/manager/src/utils/toPascalConvert.ts, packages/manager/src/views/SLA/SLAPage.tsx, packages/manager/src/views/SLA/index.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/AddMembers.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/index.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/types.ts, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/ConfigureAccess.tsx, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/index.tsx, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/types.ts, packages/manager/src/views/WebPropertyEnvPage/components/EditAccess/EditMemberAccess.tsx, packages/manager/src/views/WebPropertyEnvPage/components/EditAccess/index.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
1) RBAC Features
- AddMembers --> Adds individual and rover group to the property
- ConfigureAccess --> Configure access for peoplr in property in bulk
- Edit access --> Edits single member
- services --> has hooks used for RBAC
- toPascalCase --> converts the headers to Pascal case in tables
2) SLA
- SLA information
No
<details>
</details>
=> feat(manager) : RBAC and SLA Page

packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/AddMembers.tsx, packages/manager/src/views/WebPropertyEnvPage/components/ConfigureAccess/ConfigureAccess.tsx
=> fix(manager) : no return lint rule and fixing configure add perm

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : health check path issue resolved
1. Custom error message added for health check path
2. Health Check path default value issue resolved 
NO
<details>
</details>
=> fix(api) : health check path issue resolved

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : update ssr attribute issue resolved
1. Update SSR details issue 
2. Distinguish details for two records with same name
NO
<details>
</details>
=> fix(api) : update ssr attribute issue resolved [testing]

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : update ssr attribute issue resolved
1. Update SSR details issue 
2. Distinguish details for two records with same name
NO
<details>
</details>
=> fix(api) : update ssr attribute issue resolved

packages/api/src/configuration/index.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
1. default access url added for the SSR
2. invalid stream message changed
3. default updating added
NO
<details>
</details>
=> feat(api) : default access url added for the SSR and message changed

packages/api/src/configuration/index.ts
Subject:  fix(api) : error message changed for image url
1.  Error Message Changed 
NO
<details>
</details>
=> fix(api) : error message changed for image url

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : Config updating while deployment
1.  Configuration updating while deployment
NO
<details>
</details>
=> fix(api) : Config updating while deployment

packages/manager/src/views/WebPropertyListPage/components/WebPropertyCard/WebPropertyCard.tsx
Made alignment proper
No
<details>
</details>
=> fix(manager) : Made alignment proper

packages/api/src/server/application/service/application.service.ts
=> fix(api) : SSR path for QA

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/services/ssr/types.ts, packages/manager/src/styles/globals.css, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx, packages/manager/src/views/WebPropertyEnvPage/components/AddMembers/AddMembers.tsx
Adding Tooltips
<details>
</details>
=> feat(manager) : Fixed SSR Bugs

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
=> feat(manager): Fixing linting issue in SSR

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
web propperty
detailed page
<details>
</details>
=> feat(manager): Adding wordwrap to the tables and making ellipsis characters to 100 

packages/api/src/server/application/application.controller.ts
Subject:  fix(api) : invalid name issue resolved
1.  Checking for // added in the Name
NO
<details>
</details>
=> fix(api) : invalid name issue resolved for //

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
=> feat(manager): Setting ellipsis length to 25 for internal access URL

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx, packages/manager/src/views/WebPropertyListPage/components/WebPropertyCard/WebPropertyCard.tsx
=> feat(manager): Making HeathCheck path to prepopulate on path value initially and fixing webproperty spacing

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : SSR changed to Containerized
NO
<details>
</details>
=> fix(api) : SSR changed to Containerized

packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
1) Fixed the form fields length
2) Updated tooltip messages
3) Changed button text to Add New App
<details>
</details>
=> feat(manager): Fixed textbox length, changed the tooltip msgs and button text

packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
=> Ading isDisabled SSRForm while submitting, SSR tag in doc

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/cli/src/services/deployService.js
Subject:  feat(cli) : Containerized Deployment support
1.  Image attribute added in the CLI
2. Containerized Deployment support added 
3. Few message changes
NO
<details>
</details>
=> feat(cli) : Containerized Deployment support

packages/api/src/configuration/index.ts, packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : Port added into SSR service
1. Port added into SSR Service
2. Default port set to 3000
3. Port added into application colelction
NO
<details>
</details>
=> feat(api) : Port added into SSR service

packages/api/src/app.module.ts, packages/api/src/repository/data-services.abstract.ts, packages/api/src/repository/mongo/model/documentation.model.ts, packages/api/src/repository/mongo/model/index.ts, packages/api/src/repository/mongo/mongo-data-services.module.ts, packages/api/src/repository/mongo/mongo-data-services.service.ts, packages/api/src/server/auth/auth.guard.ts, packages/api/src/server/document/documentation.controller.ts, packages/api/src/server/document/documentation.dto.ts, packages/api/src/server/document/documentation.entity.ts, packages/api/src/server/document/service/documentation.factory.ts, packages/api/src/server/document/service/documentation.module.ts, packages/api/src/server/document/service/documentation.service.ts
Subject:  feat(api) : documentation services added [internal apis]
1.  Documentation schema, service added
2. Documentation Endpoints added for Creating, deleting and Updating Doc (Internal APIs)
3. Grouped APIs added for Document 
NO
<details>
</details>
=> feat(api) : documentation services added [internal apis]

packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx
To Implement Pagination in API Key Section
No
[screen-capture (26).webm](https://user-images.githubusercontent.com/56580582/225264459-a255ad5e-3952-4b07-a9a1-82456cc86c6b.webm)
=> feat(manager): Pagination Added to API Key Section in SPAship

packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : warning message added for the deployment
1.  feat(api) : warning message added for the deployment
2. if there any other application exits for the same path it will show those in warning
NO
<details>
</details>
=> feat(api) : warning message added for the deployment

packages/api/src/repository/mongo/model/index.ts
=> fix(api) : build fix for doc

packages/api/src/repository/mongo/model/index.ts
Subject: fix(api) : build fix for api
NO
<details>
</details>
=> fix(api) : build fix for api

packages/api/src/server/api-key/service/apikey.service.ts
Subject:  feat(api): deafult sort added for api keys
1.  Default sort added for the API Keys
NO
<details>
</details>
=> feat(api): deafult sort added for api keys

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
=> feat(api) : sync & auth added

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/index.tsx
adding dashboard tab in webproperty detaiuled page which shows stats for that webproperty based on env and  avg time to deploy
<details>
</details>
=> feat(manager): Dashboard 2.0

packages/manager/src/config/orchestratorReq.ts, packages/manager/src/layouts/AppLayout/components/Nav/Nav.tsx
=> feat(manager): JWT refresh token 

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : ssr identifier issue resolved
1.  _ handled for the application identifier
2. convert special chars to -
NO
<details>
</details>
=> fix(api) : ssr indentifier issue resolved

packages/manager/src/config/orchestratorReq.ts, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx
To add validation for Pagination Input Field, and remove input of special character and alphabetic characters
No
=> fix(manager): Added validation for pagination input field

packages/manager/src/services/spaProperty/types.ts, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
1. The healthcheck path and the path field is not having / set as default
2. The health-check path is not taking values from the path attribute
3. When i am going inside spadetail, the name is coming as the property name. whether that was expected? ( the deployment is not happening for the spa which is selected)
4. Added port in the SSR form
<details>
</details>
=> feat(manager) : Fixing containerized deployment reviews and adding port to the section

packages/manager/src/views/LoginPage/LoginPage.tsx, packages/manager/src/views/LoginPage/components/Nav/Nav.tsx
=> fix(manager):Accessibility Errors and Warnings fixed on Login Page

packages/manager/src/services/documents/index.ts, packages/manager/src/services/documents/queries.tsx, packages/manager/src/services/documents/types.ts, packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
=> feat(manager): Pulling Document details from the api, removing links

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx
1. Adding total deployment count and avg time to deploy tiles at the top in the Application dashboard
2. making it non clickable
<details>
</details>
=> feat(manager): Adding total deployment count and avg time to deploy in the Application dashboard

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
=> feat(manager):Fixing port validations, making validations to come on focus change and image URL generic message

packages/manager/src/views/DocumentsPage/DocumentsPage.tsx
=> feat(manager): href to linkhere to resolve build issue

packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx
=> feat(manager): Adding link redirection on setting button in application detailed page

packages/api/package-lock.json, packages/api/package.json
Subject:  feat(api) : version bump
1.  API Version Bump
NO
<details>
</details>
=> feat(api) : version bump to 3.2.1

packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx
=> feat(manager): Fixing port number to be less than 65536 and empty graph with no history for new property

packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  chore(api) : validations & service changes for workflow 3.0
1. Validations added for allowing only Github and GItlab hosts
2. Commit and Merge Id update issue resolved
3. isGit added into the get api for filtering
NO
<details>
</details>
=> chore(api) : validations & service changes for workflow 3.0

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/event/service/event.service.ts
Subject:  fix(api) : gitlab docker access issue and activity stream message 
1. Access url issue resolved 
2. Activity stream message formatted
3. Lint and docker access issues resolved
NO
<details>
</details>
=> fix(api) : access url issue, activity stream formatted

packages/api/src/server/application/service/application.service.ts
Subject:  chore(api) : message change for activity stream
1.  Minor change in event message
NO
<details>
</details>
=> chore(api) : minor change in event message

packages/manager/src/services/ssr/types.ts, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/types.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx
=> feat(manager): Making initial state of build args as an array, allowing special chars in branch name

packages/api/package-lock.json, packages/api/package.json, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  chore(api) : dockerFilePath support added for the deployment request 
1.  dockerFilePath added for the deployment request to operator
2. applicationIdenfier checked into validation
3. version bumped to 3.3.0
NO
<details>
</details>
=> chore(api) : dockerFilePath support added for the deployment request 

packages/api/src/server/application/service/application.service.ts
Subject: fix(api) : Public added in the exception message
1.  Message changed
NO
<details>
</details>
=> fix(api) : Public added in the exception message

packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/spaProperty/index.tsx, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/services/ssr/queries.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/Access.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
1. UI modifications to enable status checking before displaying the application link during containerized deployment
2. the deletion of key-value pair in the build config and deployment config is happening always from bottom
3. Enable Sync from the SPAship Manager
4. Clent side exception fix
<details>
</details>
=> Feat(Manager): Application status, Delete from bottom bug in form and Sync for Eph env

packages/api/package-lock.json, packages/api/package.json, packages/api/src/app.module.ts, packages/api/src/server/health/health.controller.ts, packages/api/src/server/health/service/health.module.ts, packages/api/src/server/health/service/health.service.ts
Subject:  feat(api) : database heath check service added 
1.  database health check added
2. separate endpoint created for specific status and error log check
3. ^@nestjs/terminus dependency added for health check
4. version bumped to 3.3.1
NO
<details>
</details>
=> feat(api) : database heath check service added

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
=> feat(manager): Fixing NA in access URL and adding status check on static deployments

packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
=> feat(manager): Ephemeral  env NA access URL handled

packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
=> feat(Manager): Replacing NA with spinner in accessURL

packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
=> feat(Manager): Eph access URL status checking

packages/manager/package-lock.json, packages/manager/package.json
=> feat(manager) : Updating version number for release

packages/api/src/configuration/index.ts
Subject:  chore(api) : updated the length for apikey days
1.  Updated the length limit for APIkey
NO
<details>
</details>
=> chore(api) : updated the length for apikey days

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
=> feat(Manager): fixing build issue

packages/manager/.eslintrc.js, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/CreateAPIKeyForm/CreateAPIKeyForm.tsx
=> feat(Manager):  Masking secrets in review section of form and handling NA in never expire key

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : secretMap in payload issue resolved
1. SecretMap added into the Payload
NO
<details>
</details>
=> fix(api) : secretMap in payload issue resolved

packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx
=> feat(Manager): Aligning the checkbox and creation a secret section the containerized form

packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx
=> feat(Manager):Fixing show secret toggle behaviour in containerised deployment

packages/manager/src/views/SLA/SLAPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx
=> feat(Manager): fixing secret while configuring and soumya email change in SLA Page

packages/api/package-lock.json, packages/api/package.json, packages/api/src/server/application/service/application.service.ts
Subject:  chore(api) : config change & version upgrade to 3.4.0
1.  API Version upgraded to 3.4.0
2. Config req added
NO
<details>
</details>
=> chore(api) : config change & version upgrade to 3.4.0

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
=> chrore(manager) : fix no logs error for workflow 3.0 & version upgrade

packages/manager/src/services/appLogs/queries.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
=> feat(manager): View logs spinner fix

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
=> feat(Manager): Fixing no build logs for wf2.0

catalog-info.yml, catalog/systems/SPAship.yml, packages/api/catalog-info.yml, packages/cli/catalog-info.yml, packages/manager/catalog-info.yml
DEE-204
Added configurations to include SPAship components to the Backstage catalog
No
=> DEE-204 - Added configurations to include SPAship components to the Backstage catalog

packages/api/src/app.module.ts, packages/api/src/configuration/index.ts, packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/repository/mongo/model/property.model.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/environment/service/environment.factory.ts, packages/api/src/server/environment/service/environment.service.ts, packages/api/src/server/event/service/event.service.ts, packages/api/src/server/property/property.dto.ts, packages/api/src/server/property/property.entity.ts, packages/api/src/server/property/service/property.factory.ts, packages/api/src/server/sot/cmdb/cmdb.controller.ts, packages/api/src/server/sot/cmdb/cmdb.response.dto.ts, packages/api/src/server/sot/cmdb/service/cmdb.factory.ts, packages/api/src/server/sot/cmdb/service/cmdb.module.ts, packages/api/src/server/sot/cmdb/service/cmdb.service.ts
Subject:  feat(api) : CMDB code support added with sync and multi cluster deployment 
1.  CMDB APIs integrated
2. CMDB code support added for the Property
3. Severity level based deployment added
4. Sync added for every deployment if possible
5. Multi cluster deployment added
6. Multi Cluster log support added
7. Changes in Model, DTO, Entity, Services & Controller
NO
<details>
</details>
=> feat(api) : CMDB code support added with sync and multi cluster deployment 

packages/api/src/configuration/index.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/environment/service/environment.service.ts, packages/api/src/server/property/property.controller.ts, packages/api/src/server/property/service/property.factory.ts, packages/api/src/server/property/service/property.service.ts
Subject: feat(api) : update property and env details for CMDB 
1. Update Property and env details for CMDB
2. Default value set to CMDB if not present
3. New Env variables added for analytics
NO
<details>
</details>
=> feat(api) : update property and env details for CMDB 

packages/api/src/configuration/index.ts, packages/api/src/server/analytics/service/analytics.service.ts
Subject: feat(api) : changes in developer metrics payload and envs
1.  Changes in Envs
2. Changes in payload
3. Total cost added
NO
<details>
</details>
=> feat(api) : changes in developer metrics payload and envs

packages/manager/src/links.ts, packages/manager/src/pages/developerMetrics.tsx, packages/manager/src/services/analytics/index.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/analytics/types.ts, packages/manager/src/services/developerDashboard/index.ts, packages/manager/src/services/developerDashboard/queries.tsx, packages/manager/src/services/developerDashboard/types.ts, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DeveloperMetricsDashboard/DeveloperMetricsDashboard.tsx, packages/manager/src/views/DeveloperMetricsDashboard/index.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
Implement the design to show monthly trend of efforts saved by spaship
<details>
</details>
=> feat(Manager) : Developer Metrics Dashboard

packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts, packages/api/src/server/property/property.dto.ts
Subject:  chore(api): cmdb code added into operator request
1.  CMDB Code added into operator payload
2. changes done for Static, Workflow 2.0, 3.0
3. CMDB, Severity set as optional in Property request
NO
<details>
</details>
=> chore(api): cmdb code added into operator request

packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : autoSync service added for the applications
1.  AutoSync api added for enable Sync for Specific Application
2. Call the Sync for AutoSync is ebaled and Sync is present for the specific application
3. Change in Entity, Model, New Service added for AutoSync operations
NO
<details>
</details>
=> feat(api) : autoSync service added for the applications

packages/api/src/server/application/application.controller.ts, packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  feat(api) : application deletion service added
1.  Application deletion service added
2. Support for Static Application deletion added
3. Prod Application deletion restricted
4. API created for the Deletion
5. Changes in Services and DTO 
NO
<details>
</details>
=> feat(api) : application deletion service added

packages/api/src/server/property/property.response.dto.ts, packages/api/src/server/property/service/property.service.ts
Subject:  chore(api) : cmdb & sevirity added in the response
1.   cmdb & sevirity added in the response
NO
<details>
</details>
=> chore(api) : cmdb & sevirity added in the response

packages/manager/src/services/appLogs/queries.tsx, packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/services/webProperty/index.tsx, packages/manager/src/services/webProperty/queries.tsx, packages/manager/src/services/webProperty/types.ts, packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx, packages/manager/src/views/WebPropertyEnvPage/components/SyncServiceForm/SyncServiceForm.tsx, packages/manager/src/views/WebPropertyListPage/WebPropertyListPage.tsx
=> feat(manager): Adding CMDB details in Add property page and Logs Page

packages/api/src/server/analytics/service/analytics.module.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/event/service/event.module.ts, packages/api/src/server/property/service/property.service.ts
Subject:  chore(api) : response change in login screen api
1.  Response changed for Login Screen API
2. Exceptions added for all the aggregator calls (Aggregator normally returns [] by default if no data is there, but we've also added the exceptions for the worst case scenario)
3. Code formatted
NO
<details>
</details>
=> chore(api) : response change in login screen api

packages/api/src/server/analytics/analytics.controller.ts, packages/api/src/server/analytics/service/analytics.service.ts, packages/api/src/server/property/service/property.service.ts
Subject:  feat(api) : developer dashboard api refactored for the user mode
1.  developer dashboard api refactored for the user mode
2. user input added for the averageTimeSaved
3. spaship-admin mode provided for the complete metrics
4. Exception handled & Throw error if no data present in the database (edge case)
5. Code formatted 
NO
<details>
</details>
=> feat(api) : developer dashboard api refactored for the user mode

packages/manager/Dockerfile
=> feat(Manager): Fixing build issue 

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/pages/login.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/AddWebPropertyPage/AddWebPropertyPage.tsx, packages/manager/src/views/DashboardPage/DashboardPage.tsx, packages/manager/src/views/DashboardPage/components/DashboardChart/DashboardChart.tsx, packages/manager/src/views/LoginPage/LoginPage.tsx, packages/manager/src/views/LoginPage/components/Nav/Nav.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx
Follow the steps to create the PR:
Subject: "feat/fix/docs(#issue_id): <PR Subject>"
Assignees: "Developers"
Projects: "SPAship"
-->
1. Data filteration at global, Web property and spa, property level, dashboard for activity stream, upper tiles as well as charts.
2. Added Empty State, for no data found for both charts as well as handled infinity is in the guard at the top.
3. Modified activity stream messages with property and spa names in the message.
4. Added metrics in the login screen as well
5. Fixed all bigs mentioned by QE in first testing
<details>
</details>
=> feat(manager) : Dashboard and login screen design revamp

packages/api/src/server/analytics/service/analytics.service.ts
Subject:  fix(api) : changes in the api for login screen
1. Changes in the API for the login screen
2. Add total deployment count
NO
<details>
</details>
=> fix(api) : changes in the api for login screen

packages/api/src/repository/mongo/model/application.model.ts, packages/api/src/server/application/application.entity.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject: chore(api) : route url provision added for the static deployment
1.  RouteUrl added in the schema
2. Route URL provision added for the Static Deployments
3. Generate Route URL for every static deployment
NO
<details>
</details>
=> chore(api) : route url provision added for the static deployment

packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/ephemeral/types.ts, packages/manager/src/services/spaProperty/types.ts, packages/manager/src/services/ssr/queries.tsx, packages/manager/src/services/ssr/types.ts, packages/manager/src/services/sync/index.tsx, packages/manager/src/services/sync/queries.tsx, packages/manager/src/services/sync/types.ts, packages/manager/src/services/webProperty/queries.tsx, packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/DashboardPage/components/DashboardChart/DashboardChart.tsx, packages/manager/src/views/LoginPage/components/Nav/Nav.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Dashboard/Dashboard.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/Access.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/types.tsx, packages/manager/src/views/WebPropertyEnvPage/WebPropertyEnvPage.tsx
1. CMDB field made required
2. Client-Side exception in the setting page
3. Login page slack link issue
4. enabling auto sync for static SPA
5. Enabling multiple access URLs
6. Activity stream refreshing
7. Ephemeral time calculation correction
<details>
</details>
=> feat(Manager): AutoSync Enabled, Login Slack opening in new tab and Eph time correction

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : log removed & ephemeral issues resolved
1.  Secret Logs Removed
2. Ephemeral issue resolved 
NO
<details>
</details>
=>  fix(api) : log removed & ephemeral issues resolved

packages/api/package-lock.json, packages/api/package.json, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js, packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/services/ephemeral/types.ts, packages/manager/src/styles/globals.css, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SSRDetails.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
Subject:  feat(spaship) : manager, api & CLI changes added
1.  Changes in Manager added 
2. Version bump for API
3. Changes in CLI added (already verified)
Note : All the changes for CLI (duration) & API (Version bump) are already verified, we're rearraging the commits because for one Infosec issue
NO
<details>
</details>
=> feat(spaship) : manager, api & CLI changes added for 23.08.0 release

packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx
…e and adding CMDB tooltip (#2443)
* adding CMDB details in property page
* CMDB field made required
* Enabling autosync for static spa
* deleting temp file
* resolving conflicts
* Implementing logs new design
* Fixing multiple entires of URLs and css issue with tab text
<details>
</details>
=> feat(manager) : Adding google form link in feedback section

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject: feat(api) : router url configured for containerized deployments
1. Router URL added for the Workflow 2.0 & 3.0 Deployments 
2. Router URL added to the Application Response (Access URL) for all types of deployment
NO
<details>
</details>
=> feat(api) : router url configured for containerized deployments

packages/api/src/configuration/index.ts, packages/api/src/server/auth/auth.guard.ts, packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/environment/service/environment.service.ts
Subject:  feat(api) : api added to get env list by git repo
1.  New API Added to get Env list by the Git Repository URL and Context Directory
2. API added in the git broker auth (to be consumed from the git broker)
3. Changes in Config variable 
NO
<details>
</details>
=> feat(api) : api added to get env list by git repo

.github/workflows/manager-ci.yaml
Subject:  chore(ci) : new build args added for spaship manager
1.  Changes in CI for the new Build Args
NO
<details>
</details>
=> chore(ci) : new build args added for spaship manager

packages/manager/src/components/Banner/Banner.tsx, packages/manager/src/components/Radio/radio.module.css, packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/layouts/AppLayout/components/Nav/Nav.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/HomePage/HomePage.tsx, packages/manager/src/views/StayTunedPage/StayTunedPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
1. Settings Page toggle button
2. Web property page redirection from the sidebar and actual onclick property fixed
3. Fixed selected property name in dropdown in the sidebar 
4. Moved pagination to the top side as the view logs section was overlapping.
5. Make the view logs section aligned in the center. 
<details>
</details>
=> feat(manager) : big fixes for manager revamp phase 3

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
=> feat(Manager): Fixing client side exception in activity stream redirection to static and containerized subsection 

packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/Settings/Settings.tsx, packages/manager/src/views/Settings/components/ApiKey/CreateAPIKeyForm/CreateAPIKeyForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx
Following bug fixes 
1. Fixing create API key form on submit with error issue
2. Renaming documents
3. changing select web property to my property and handling the redirection
4. shifting pagination for list of spas to top
<details>
</details>
=> feat(Manager) : Fixing API Key onsubmit bug | renaming documents tab and select my property

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : changes in the message for ephemeral preview
1.  Message changed for preprod env not found in ephemeral env
NO
<details>
</details>
=> fix(api) : changes in the message for ephemeral preview

packages/api/src/server/application/service/application.service.ts
Subject:  chore(api): ephemeral service refactored into functions
1.  Ephemeral service converted into function (refactored)
3. No changes in the existing code
4. Ephemeral added for wf 3.0
NO
<details>
</details>
=> chore(api): ephemeral service refactored into function

packages/manager/src/views/Settings/components/Environment/Environment.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
=> feat(Manager): fixing redirection for SSR 2.0 spa name click

packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject: fix(api) : config and secret issue in first deployment resolved
1.  Initial deployment config and secret 400 issue fixed
2. Value coming for secret in first deployment fixed
NO
<details>
</details>
=> fix(api) : config and secret issue in fisrt deployment resolved

packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx
1. Now configure secrets to show by default value as ***** in password value and you can directly edit it.
2. Fixing lint and build issues.
<details>
</details>
=> feat(Manager): Modifying configure secrets form in configure App

packages/manager/src/services/persistent/index.tsx, packages/manager/src/services/persistent/queries.tsx, packages/manager/src/services/persistent/types.ts, packages/manager/src/views/Settings/Settings.tsx, packages/manager/src/views/Settings/components/Symlink/CreateSymlink/CreateSymlink.tsx, packages/manager/src/views/Settings/components/Symlink/CreateSymlink/index.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx, packages/manager/src/views/Settings/components/Symlink/index.tsx
1. Added a form to create a symlink from manager
2. Showing list of symlinks created in separate section in settings tab
<details>
</details>
=> feat(Manager): Adding create symlink support from manager

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
=> environment filter in container and static

packages/manager/src/views/Settings/components/Symlink/CreateSymlink/CreateSymlink.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
1. fixed validation failing for source and target file path
<details>
</details>
=> feat(Manager): Fixing validation bug in create symlink form

packages/api/src/configuration/index.ts, packages/api/src/repository/mongo/model/environment.model.ts, packages/api/src/server/environment/environment.controller.ts, packages/api/src/server/environment/environment.dto.ts, packages/api/src/server/environment/environment.entity.ts, packages/api/src/server/environment/service/environment.factory.ts, packages/api/src/server/environment/service/environment.service.ts
Subject: feat(api) : symlink service added into orchestrator
1. Symlink DTO added with validations
2. Changes in Environment entity and model
3. Symlink API and Service added
4. Operator call added for the symlink
5. New end point added
NO
<details>
</details>
=> feat(api) : symlink service added into orchestrator

packages/manager/src/components/Banner/Banner.tsx, packages/manager/src/layouts/AppLayout/components/Nav/Nav.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx
1. Secrets masking used to go away when there was no updated value, now its fixed to stay when not in focus
2. Secrets are masked in review section of the form as well
3. Sidebar dropdown is renamed as Select My property and did the changes according to the design
4. Made Home breadcrumb clickable
5. Removed Docs section from navbar
<details>
</details>
=> feat(Manager) :Fixing bugs in sidebar revamp dropdown and secrets section in form

packages/manager/src/services/persistent/types.ts, packages/manager/src/views/Settings/components/Symlink/CreateSymlink/CreateSymlink.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
1. Adding support for multiple symlinks
2. fixing textbox bugs
<details>
</details>
=> feat(Manager): adding support for multiple symlinks and fixing textbox length

packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/styles/globals.css, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
=> Feat(manager): Fixing no property found for user and CSS for select dropdown

packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
=> feat(Manager): Fixing textcenter of header in Symlink table

packages/api/src/server/environment/environment.dto.ts
Subject:  chore(api) : validations removed for source & target
NO
<details>
</details>
=> chore(api) : validations removed for source & target

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
=> feat(Manager) : Adding support for multiple symlinks and fixing textbox

packages/api/package-lock.json, packages/api/package.json
Subject: version(api) : version bump for orchestrator to 4.1.0
1.  Version upgrade to orchestrator
NO
<details>
</details>
=> version(api) : version bump for orchestrator to 4.1.0

packages/manager/src/views/Settings/components/Symlink/CreateSymlink/CreateSymlink.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
=> feat(Manager): Removing helper text from source and target fields in symlink

packages/api/src/server/application/application.dto.ts, packages/api/src/server/application/service/application.factory.ts, packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : containerized deployment config update issue resolved
1. Containerized Deployment (workflow 2.0) config update Deployment Issue Resolved
NO
<details>
</details>
=> fix(api) : containerized deployment config update issue resolved

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
Adding application available and unavailable in activity stream
<details>
</details>
=> feat(Manager): Adding application available and unavailable in activity stream

packages/api/src/server/application/service/application.factory.ts
Subject:  fix(api) : containerized deployment request payload issue resolved
1.  SSR request payload issue resolved
NO
<details>
</details>
=> fix(api) : containerized deployment request payload issue resolved

packages/api/src/server/application/service/application.service.ts
Subject:  fix(api) : config update issue fix for CLI deployment
1. Config auto update issue fix for the CLI deployment
NO
<details>
</details>
=> fix(api) : config update issue fix for CLI deployment

packages/manager/src/context/AuthGuard/AuthGuard.tsx, packages/manager/src/pages/_app.tsx, packages/manager/src/views/Settings/components/Symlink/Symlink.tsx
=> feat(Manager): Logout when token expires

packages/manager/src/context/AuthGuard/AuthGuard.tsx, packages/manager/src/pages/_app.tsx
1. Added a global error handler for unauthorized status 401
<details>
</details>
=> feat(Manager): Fixing spaship crashing issue because of token expiration

packages/api/package-lock.json, packages/api/package.json
Subject:  version(api) : version upgraded for the patch
1.  Version upgraded for the Patch
NO
<details>
</details>
=> version(api) : version upgraded for the patch

packages/api/src/server/lighthouse/dto.ts, packages/api/src/server/lighthouse/service/factory.ts
Subject: chore(api) : build lighthouse metrics with the required values
1.  Values extracted from the lighthouse report
NO
<details>
</details>
=> chore(api) : build lighthouse metrics with the required values

packages/api/src/server/application/service/factory.ts
Subject:  fix(api) : few http status code allowed for access url
1. Except 503 all the status code allowed as a valid available access url
NO
<details>
</details>
=> fix(api) : http status codes allowed for access url 

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
Closes #issue_id
Implemented an "Environment Filter" on the SPA Detailed Page, which allows stakeholders to filter and view all SPAs within a specific environment. This feature provides a convenient way for stakeholders to search and access relevant information, enhancing the user experience.
No
<details>
</details>
=> feat(manager) : environment filter in spa details page

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx
Closes #issue_id
fixed grammatical error for spa details page
no
<details>
</details>
=> fix(manager) : fixed grammatical error in EmptyStateBody

packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ApplicationStatus.tsx
=> feat(Manager) : Fixing client side exception due to router URL and access URL not available

packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Applications/ApplicationsListPage.tsx
1. functionality to Generate new lighthouse report for existing spa
2. added redirection for env details button web properties page
<details>
</details>
=> feat(manager) : generate new lighthouse report for existing spa

packages/api/src/server/application/service/factory.ts
Subject:  fix(api) : route url unavailabe issue resolved
1.  route url unavailable issue resolved
2. access http url issue resolved
3. 301 status code handled 
NO
<details>
</details>
=> fix(api) : route url unavailabe issue resolved

.github/workflows/manager-ci.yaml
Subject:  chore(ci) : lighthouse url added as the build arg in manager
1.  Lighthouse url added into the CI for manager
NO
<details>
</details>
=> chore(ci) : lighthouse url added as the build arg in manager

packages/manager/src/services/lighthouse/queries.tsx, packages/manager/src/utils/convertDateFormat.ts, packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Applications/ApplicationDetailsSection.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Applications/ApplicationsListPage.tsx
=> feat(manager): Fixing date formats and generate score toast fix 

packages/api/src/server/lighthouse/controller.ts
Subject: fix(api) : isContainerized query issue resolved
1.  isContainerized query issue resolved
NO
<details>
</details>
=> fix(api) : isContainerized query issue resolved

packages/api/src/server/lighthouse/service/factory.ts
Subject: fix(api) : lighthouse identifier for git fixed
1.  lhIdentifier resolved for git
NO
<details>
</details>
=> fix(api) : lighthouse identifier for git fixed

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/services/lighthouse/queries.tsx, packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
1.  Empty state for no lighthouse data.
2. Disabling button when lighthouse data is not there
3. Adding lighthouse events in activity stream
4. Handling empty ids for lighthouse for given spa
5. Refreshing lighthouse data for same env name and isgit diff for containerized
6. Handling memory leak issue in web properties and spa properties page
<details>
</details>
=> feat(manager) : Lighthouse bugs

packages/api/src/configuration/index.ts, packages/api/src/server/lighthouse/service/factory.ts
Subject: chore(api) : ref added for lighthouse ci added
1.  ci ref added into ref variable
NO
<details>
</details>
=> chore(api) : ref added for lighthouse ci added

packages/api/src/server/lighthouse/service/factory.ts, packages/api/src/server/lighthouse/service/index.ts
Subject: chore(api) : lighthouse error message changed
1. lighthouse error message changed
NO
<details>
</details>
=> chore(api) : lighthouse error message changed

packages/api/src/configuration/index.ts, packages/api/src/server/lighthouse/service/index.ts
Subject: fix(api) : router url exception added
1.  Router url exception added
2. config var issue resolved
NO
<details>
</details>
=> fix(api) : router url exception added

packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Applications/ApplicationDetailsSection.tsx
=> feat(Manager): Fixing router URL and view logs sections

packages/api/src/server/lighthouse/service/factory.ts
Subject: fix(api) : max limit added for the lh indentifier
1.  max limit added for the lh indentifier
NO
<details>
</details>
=> fix(api) : max limit added for the lh indentifier

packages/api/package-lock.json, packages/api/package.json
Subject: version(api) : version updated to 4.2.0
1. api version updated to 4.2.0 
NO
<details>
</details>
=> version(api) : version updated to 4.2.0

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx
=> feat(Manager): Updating version of spaship manager v3.1.0

packages/api/src/configuration/index.ts
Subject: chore(api) : severity updated for C3, C4, C5
1.  C3,. C4, C5 severity added for the prod cluster
NO
<details>
</details>
=> chore(api) : severity updated for C3, C4, C5

packages/manager/src/views/SPAPropertyDetailPage/Lighthouse/Lighthouse.tsx
=> feta(Manager): Changing lighthouse url variable

packages/api/src/app.module.ts, packages/api/src/repository/data-services.abstract.ts, packages/api/src/repository/mongo/model/feedback.ts, packages/api/src/repository/mongo/model/index.ts, packages/api/src/repository/mongo/mongo-data-service.service.ts, packages/api/src/repository/mongo/mongo-data-services.module.ts, packages/api/src/server/feedback/controller.ts, packages/api/src/server/feedback/dto.ts, packages/api/src/server/feedback/entity.ts, packages/api/src/server/feedback/service/factory.ts, packages/api/src/server/feedback/service/index.ts, packages/api/src/server/feedback/service/module.ts
Subject: feat(api) : feedback module added
Assignees: @soumyadip007 @nikhitamore 
1.  Feedback module added
NO
<details>
</details>
=> feat(api) : feedback module added 

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/Feedback/Feedback.tsx, packages/manager/src/components/Feedback/declarations.d.ts, packages/manager/src/components/Feedback/index.tsx, packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/pages/feedback-dashboard.tsx, packages/manager/src/services/feedback/index.tsx, packages/manager/src/services/feedback/queries.tsx, packages/manager/src/services/feedback/types.tsx, packages/manager/src/views/FeedbackDashboard/UserFeedbackDashboard.tsx, packages/manager/src/views/FeedbackDashboard/index.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx
-Frontend
1. Implemented the opc-feedback component.
2. Excluded integration code for services from one platform.
3. Integrated the creation of feedback with the spaship service.
4. Established a user feedback dashboard to showcase submitted feedback.
5. Eliminated the feedback tab from the sidebar.
6. Incorporated hooks for adding and displaying user feedback.
7. Assigned IDs for containerized and static SPA page elements.
<details>
</details>
=> feat(manager): Feedback component with one platform service integrated

packages/api/src/configuration/index.ts, packages/api/src/server/environment/dto.ts, packages/api/src/server/environment/service/factory.ts, packages/api/src/server/environment/service/index.ts
Subject: chore(api) : symlink service updated
1.  Symlink service updated
NO
<details>
</details>
=>  chore(api) : symlink service updated

packages/api/src/server/api-key/controller.ts, packages/api/src/server/api-key/service/index.ts
Subject: chore(api) : validate apikey point added
1.  Validate APIkey end point added
NO
<details>
</details>
=> chore(api) : validate apikey point added

packages/manager/src/components/Feedback/Feedback.tsx, packages/manager/src/services/persistent/index.tsx, packages/manager/src/services/persistent/queries.tsx, packages/manager/src/services/persistent/types.ts, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/CreateStaticApp/CreateStaticApp.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/CreateStaticApp/index.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx
1. Added feature to add static distribution from spaship manager
<details>
</details>
=> feat(Manager): Adding static upload functionality from Manager

.github/workflows/manager-ci.yaml
Subject: chore(ci) : gitbroker url added as the build arg in manager
1.  gitbroker url added as the build arg in manager
NO
<details>
</details>
=> chore(ci) : gitbroker url added as the build arg in manager

packages/api/src/server/environment/service/index.ts
=> feat(api): removing the auto environment initialization

packages/manager/src/components/Feedback/Feedback.tsx, packages/manager/src/views/FeedbackDashboard/UserFeedbackDashboard.tsx
…onal | added redirection to spaship
<details>
</details>
=> feat(Manager): feedback module : Changed the column sizes | made the summary field optional | added redirection to spaship

packages/api/package-lock.json, packages/api/package.json, packages/api/src/configuration/index.ts
Subject: chore(api) : secret changed and version updated
1.  secret changed 
2. version updated to 4.3.0
NO
<details>
</details>
=> chore(api) : secret changed and version updated

packages/manager/package-lock.json, packages/manager/package.json, packages/manager/src/components/Feedback/Feedback.tsx
…onal | added redirection to spaship
<details>
</details>
=> feat(Manager): Updating version number to 3.2.0

packages/manager/src/context/AuthGuard/AuthGuard.tsx, packages/manager/src/views/LoginPage/LoginPage.tsx
=> feat (manager): Fixing redirection issue after login

packages/api/src/server/application/controller.ts, packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts
Subject: feat(api) : get static logs service
1. Static logs added 
NO
<details>
</details>
=> feat(api) : get static logs service

packages/api/src/server/application/service/index.ts
Subject: feat(api) : ephemeral env support added for the SSR
1. ephemeral env support added for the SSR
NO
<details>
</details>
=> feat(api) : ephemeral env support added for the SSR

packages/api/src/configuration/index.ts, packages/api/src/server/application/controller.ts, packages/api/src/server/application/service/index.ts
=> feat(api) : ephemeral env support added for the SSR updating chaturdocs branch with master

packages/api/src/configuration/index.ts, packages/api/src/server/application/service/index.ts
Subject: chore(api): symlink job added as enum, activity stream message added
1. Job added into Enum
2. Activity stream message fixed
NO
<details>
</details>
=> chore(api): symlink job added as enum, activity stream message added

packages/api/src/server/application/controller.ts, packages/api/src/server/application/service/index.ts
Subject: feat(api) : symlink deletion added
1. Symlink deletion service added
2. API added for the Symlink deletion
NO
<details>
</details>
=> feat(api) : symlink deletion service added

packages/api/src/server/application/service/index.ts
Subject: fix: cli zip upload issue resolved for
1. CLI Zip upload issue resolved
NO
<details>
</details>
=> fix: cli zip upload issue resolved for

packages/manager/src/services/appLogs/queries.tsx, packages/manager/src/utils/extractPodIds.ts, packages/manager/src/views/SPAPropertyDetailPage/ContainerizedSPADeployment/ContainerizedSPADeployment.tsx, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ContainerizedDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/StaticDeployment.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
- The system now efficiently handles scenarios with multiple PodIDs, improving overall deployment robustness.
- Codebase improvements ensure consistent formatting and resolve linting issues, enhancing code quality and readability.
- ID duplication in both containerized and static single-page applications (SPA) has been eliminated, streamlining deployments and reducing potential errors.
<details>
</details>
=> feat(manager): Adding feature to view logs for static deployment

packages/manager/src/services/appLogs/queries.tsx, packages/manager/src/utils/extractPodIds.ts, packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment.tsx/StaticSPADeployment.tsx
=> fix(manager) : Fixing prettier issues for build

packages/api/src/server/application/service/index.ts
Subject: fix(api) : tar compression issue resolved
1. tar compression issue resolved
NO
<details>
</details>
=> fix(api) : tar compression issue resolved

packages/api/src/server/application/service/index.ts
Subject: fix(api) : symlink activity stream issue resolved
1. Symlink schedule, creation and fail specifier added into activity stream
NO
<details>
</details>
=> fix(api) : symlink activity stream issue resolved

packages/manager/src/views/Settings/Settings.tsx
=> fix(manager): remove the symlink section from the settings page.

packages/api/src/server/application/service/factory.ts
Subject: fix(api): root spa issue resolved for auto symlink creation
1. root spa issue resolved for auto symlink creation
NO
<details>
</details>
=> fix(api): root spa issue resolved for auto symlink creation

packages/manager/src/views/SPAPropertyDetailPage/StaticSPADeployment/StaticSPADeployment.tsx, packages/manager/src/views/Settings/components/Symlink/CreateSymlink/CreateSymlink.tsx
=> feat(Manager): Symlink path field modifications

packages/api/src/server/application/service/factory.ts
Subject: chore(api) : support provided for the nested symlinks
1. Support provided for the nested symlinks in SPAship
NO
<details>
</details>
=> chore(api) : support provided for the nested symlinks

packages/api/package-lock.json, packages/api/package.json
Subject: version(api): version bumped to 4.4.0
1. API Version updated
NO
<details>
</details>
/var/www/html/new/dx/v1-alpha
=> version(api): version bumped to 4.4.0

packages/manager/src/layouts/AppLayout/AppLayout.tsx
=> feat(manager): Blue banner instead of white as per Patternfly design

packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/services/persistent/queries.tsx, packages/manager/src/services/persistent/types.ts, packages/manager/src/styles/globals.css, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
1. Adjustment of the page height to eliminate the redundant scroll bar triggered by the addition of the release note banner at the top of the Splaship Manager interface.
2. Implementation of functionality enabling users to delete ephemeral environments directly from the Splaship Manager, enhancing user control and management capabilities.
<details>
for Ephemeral
and scroll bar
</details>
=> feat(Manager): Enhancements: Addressed Scroll Bar Issue and Introduced Environment Deletion Feature

packages/api/src/server/analytics/service/factory.ts, packages/api/src/server/analytics/service/index.ts, packages/api/src/server/analytics/user-analytics-response.dto.ts
Subject: chore(api) : createdBy added into the property analytics api
1. createdBy added into the property analytics api
NO
<details>
</details>
=> chore(api) : createdBy added into the property analytics api

packages/manager/package.json, packages/manager/src/components/Banner/Banner.tsx, packages/manager/src/layouts/AppLayout/components/SideBar/SideBar.tsx, packages/manager/src/services/analytics/index.tsx, packages/manager/src/services/analytics/queries.tsx, packages/manager/src/services/analytics/types.ts, packages/manager/src/services/persistent/queries.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/ReleaseNotesCard.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/Tutorials.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/Ephemeral/Ephemeral.tsx
1. Resolved property name inconsistencies and stabilized ephemeral environment bug.
2. Completed deletion functionality for removing unwanted items.
3. Finished implementation of homepage feature.
<details>
</details>
=> feat(Manager): Fixed inconsistencies in property name, Ephemeral env deletion bug, and completed homepage.

packages/api/src/server/analytics/service/index.ts
Subject: chore(api) : exceptions added in the analytics api
1. Exceptions added for the analytics api
NO
<details>
</details>
=> chore(api) : exceptions added in the analytics api

packages/api/src/server/application/request.dto.ts
Subject: fix(api) : symlink validation issue resolved
1. Symlink validation issue resolved
NO
<details>
</details>
=> fix(api) : symlink validation issue resolved

packages/api/src/repository/mongo/model/application.ts, packages/api/src/server/application/entity.ts, packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts, packages/api/src/server/sot/cmdb/dto.ts, packages/api/src/server/sot/cmdb/service/index.ts
Subject: chore(api) : severity added into application & property service
1. severity added into application & property service
2. severity added into entiry 
NO
<details>
</details>
=> chore(api) : severity added into application & property service

packages/manager/src/services/spaProperty/queries.tsx, packages/manager/src/services/webProperty/queries.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPASettingsPage/SPASettingsPage.tsx, packages/manager/src/views/Settings/components/CmdbDetails/CmdbDetails.tsx, packages/manager/src/views/Settings/components/CmdbDetails/EditCmdbDetails/EditCmdbDetails.tsx, packages/manager/src/views/Settings/components/CmdbDetails/EditCmdbDetails/index.tsx
Add an edit icon to the CMDB settings section.
Include a settings section at the SPA level.
Add a form to allow users to update the CMDB code for both properties and SPA.
Validate the entered code to ensure it is valid and prevent invalid submissions.
<details>
</details>
=> feat(Manager): Adding form to edit cmdb code at spa and property level

packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts
Subject: fix(api) : cmdb initi issue resolve for wf 2.0 and 3.0
1. CMDB code initialisation issue for the first deployment resolved 
NO
<details>
</details>
=> fix(api) : cmdb initi issue resolve for wf 2.0 and 3.0

packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx, packages/manager/src/views/Settings/components/CmdbDetails/CmdbDetails.tsx
1. Exclusion of "banner" Section: With the rollout of a new release banner, it's prudent to omit the existing "banner" section to prevent redundancy and maintain consistency in messaging across the application.
2. Homepage Review Fixes: Incorporate adjustments based on the latest homepage review to enhance usability, address any identified issues, and ensure an improved user experience upon accessing the homepage.
3. CMDB Details: Note added for adding separate cmdb at SPA details settings page and removing edit button at the property CMDB level.
<details>
1. Removed banner
2. ![image](https://github.com/spaship/spaship/assets/26894183/0cf50f71-eeaa-476b-b97b-7dba5f2df1c5)
</details>
=> feat(Manager): Refactoring: Exclude the "banner" section and address homepage issues based on the latest review

packages/api/src/server/application/service/index.ts
Subject: fix(api) : populate value from the existing updated SPA cmdb code for…
1. populate value from the existing updated SPA cmdb code fo
NO
<details>
</details>
=> fix(api) : populate value from the existing updated SPA cmdb code

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/views/DocumentsPage/DocumentsPage.tsx, packages/manager/src/views/HomePage/HomePage.tsx, packages/manager/src/views/HomePage/Homepage.css, packages/manager/src/views/HomePage/components/WebpropertiesTable/ReleaseNotesCard.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx
… web properties table.
1. Updating activity stream with cmdb code update message
2. Fetching release notes from docs api
<details>
</details>
=> feat(Manager): Updating the activity stream with CMDB code update messages and fetching release notes from the documents API

packages/api/src/server/application/service/index.ts
Subject: fix(api): cmdb update issue resolve for static deployment
1. cmdb update issue resolve for static deployment
NO
<details>
</details>
=> fix(api): cmdb update issue resolve for static deployment

packages/manager/src/layouts/AppLayout/AppLayout.tsx, packages/manager/src/views/HomePage/Homepage.css, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx
… web properties table.
<details>
</details>
=> feat(manager): Fixing table overflow on home page and feedback button overlap

packages/manager/src/config/orchestratorReq.ts, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx
… web properties table.
<details>
</details>
… web properties table.
=> feat(Manager): Fixing jwt refresh issue

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/deploy.js
Subject: chore(cli) : multiple config file support added  @soumyadip007
1. Multiple File Support added
2. Version updated
NO
<details>
</details>
=> chore(cli) : multiple config file support added  @soumyadip007

packages/api/package-lock.json, packages/api/package.json
Subject: chore(api) : version update
1. version update
NO
<details>
</details>
=> chore(api) : version update

packages/api/src/app.module.ts, packages/api/src/server/report/controller.ts, packages/api/src/server/report/response.dto.ts, packages/api/src/server/report/service/factory.ts, packages/api/src/server/report/service/index.ts, packages/api/src/server/report/service/module.ts
Subject: feat(api) : report added for all properties, envs and applications
1. Property, env and application report added
2. API added for the report
3. Service and module added for the report 
NO
<details>
</details>
=> feat(api) : report added for all properties, envs and applications

packages/api/src/server/report/response.dto.ts
Subject: chore(api) : owners and timestamp added
1. CreatedBy, UpdatedBy, CreatedAt, UpdatedAt added
NO
<details>
</details>
=> chore(api) : owners and timestamp added

packages/api/src/server/analytics/controller.ts, packages/api/src/server/analytics/service/factory.ts, packages/api/src/server/analytics/service/index.ts
Subject: feat(api): history api added for the property & application activities
1. History api added for the property and applications
2. Mongo aggregation query added for the history api
3. Provision added for passing multiple action specifiers
4. Added as Activity Stream V2 API
5. Old Activity Stream API to be deprecated
NO
<details>
</details>
=> feat(api): history api added for the property & application activities

packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts
Subject: fix(api) : router URL encode issue resolved
1. Router URL Encode issue resolved
NO
<details>
</details>
=> fix(api) : router URL encode issue resolved

packages/api/src/server/report/controller.ts
Subject: chore(api): auth guard added for the Report api
1. Auth guard added for the report api
NO
<details>
</details>
=> chore(api): auth guard added for the Report api

packages/api/src/server/property/service/index.ts, packages/api/src/server/report/controller.ts, packages/api/src/server/report/service/index.ts
Subject: feat(api) : pagination added for the report API
1. pagination added for the report API
NO
<details>
</details>
=> feat(api) : pagination added for the report API

packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts
Subject: fix(api): virtual path exception issue resolved 
1. virtual path exception issue resolved
NO
<details>
</details>
=> fix(api): virtual path exception issue resolved 

packages/api/src/server/application/service/index.ts
Subject: fix(api): virtual path exception issue resolved 
1. virtual path exception issue resolved
NO
<details>
</details>
=> fix(api): virtual path exception issue resolved

packages/api/src/server/application/entity.ts, packages/api/src/server/report/response.dto.ts, packages/api/src/server/report/service/factory.ts
Subject: feat(api) : cluster and podList structure added
1. Cluster added instead of Con
2. PodList Structure added
3. Transformer Service added
NO
<details>
</details>
=> feat(api) : cluster and podList structure added

packages/api/package-lock.json, packages/api/package.json
Subject: chore(api) : version updated to 4.6.0
1. API version updated to 4.6.0
NO
<details>
</details>
=> chore(api) : version updated to 4.6.0

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
… web properties table.
I have added a new button at the top of the logs window for fetching new logs and a "Go to Top" button for smooth navigation, enhancing user experience by making log viewing more accessible and efficient.
<details>
</details>
=> feat(manager): fix dropdown value selection and implement "Scroll to Top" functionality in logs view.

packages/api/src/server/application/service/index.ts, packages/api/src/server/environment/service/factory.ts, packages/api/src/server/environment/service/index.ts, packages/api/src/server/sot/cmdb/service/index.ts, packages/api/src/server/sot/cmdb/service/module.ts
Subject: feat(api) : update CMDB code in the POD
1. CMDB code added for the Pod Update
2. InitEnv changed into ConfigureEnv
3. Build function for env creation zip separated
4. Rebuild added for the updation of the CMDB Code
5. Only changed CMDB code will be updated in all env of the property in every cluster
NO
<details>
</details>
=> feat(api) : update CMDB code in the POD

packages/api/src/server/auth/guard.ts
Subject: chore(api) : createdBy added for static deployment from SPAship manager
1. createdBy added for static deployment from SPAship manager
NO
<details>
</details>
=> fix(api) : createdBy added for static deployment from SPAship manager

packages/api/src/server/application/controller.ts, packages/api/src/server/application/service/index.ts, packages/api/src/server/auth/guard.ts
Subject: fix(api) : source issue fixed for the deployment
1. source issue fixed for the deployment
NO
<details>
</details>
=> fix(api) : source issue fixed for the deployment

packages/api/src/server/application/service/index.ts
Subject: fix(api) : virtual path creation issue
1. virtual path creation issue
NO
<details>
</details>
=> fix(api) : virtual path creation issue

packages/manager/src/components/ActivityStream/ActivityStream.tsx, packages/manager/src/services/history/queries.tsx, packages/manager/src/views/History/History.tsx, packages/manager/src/views/SPAPropertyDetailPage/VirtualPath/VirtualPath.tsx, packages/manager/src/views/SPAPropertyDetailPage/VirtualPath/components/CreateVirtualPath.tsx
1) added API key deletion action in history section.
2) fixing message in activity stream for application deletion action.
3) Changing the header to Date & time in history section table.
<details>
</details>
=> feat(Manager): Fixing feedback from QA

packages/api/src/server/application/service/index.ts
Subject: fix(api) : NA issue fixed for the ephemeral env
1. NA issue fixed for the ephemeral env
NO
<details>
</details>
=> fix(api) : NA issue fixed for the ephemeral env

packages/api/src/server/analytics/service/factory.ts
Subject: fix(api): history data order issue resolved
1. The history data order issue was resolved
NO
<details>
</details>
=> fix(api): history data order issue resolved

packages/api/src/server/agenda/service/index.ts, packages/api/src/server/environment/controller.ts, packages/api/src/server/environment/dto.ts
Subject: fix(api): ephemeral env deletion action createdBy issue resolved
1. fix(api): ephemeral env deletion action createdBy issue resolved
NO
<details>
</details>
=> fix(api): ephemeral env deletion action createdBy issue resolved

packages/manager/package.json, packages/manager/src/styles/globals.css, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/ViewLogs.tsx
=> fix(manager): Fixing visibility of buttons and reload issue on tab focus change for logs panel

packages/manager/src/views/HomePage/components/WebpropertiesTable/DeploymentStatsCard.tsx, packages/manager/src/views/SPAPropertyDetailPage/SPAPropertyDetailPage.tsx, packages/manager/src/views/WebPropertyDetailPage/WebPropertyDetailPage.tsx
…epage stats
<details>
</details>
=> fix(manager): fixing broken settings tab and addings secs to the homepage stats

packages/api/package-lock.json, packages/api/package.json
Subject: chore(api): version updated to 4.7.0
1. API version updated to 4.7.0
NO
<details>
</details>
=> chore(api): version updated to 4.7.0

packages/api/src/server/property/service/index.ts
Subject: fix(api): property creation action createdBy issue resolved
1. property creation action createdBy issue resolved
NO
<details>
</details>
=> fix(api): property creation action createdBy issue resolved

packages/api/src/server/sot/cmdb/service/index.ts
Subject: fix(api): update cmdb code issue resolved
1. update cmdb code issue resolved
NO
<details>
</details>
=> fix(api): update cmdb code issue resolved

packages/manager/src/views/History/History.tsx, packages/manager/src/views/HomePage/components/WebpropertiesTable/WebpropertiesTable.tsx
=> fix(manager): Paginated data in homepage and empty state for history section

packages/manager/src/services/rbac/types.ts, packages/manager/src/views/Settings/components/AccessControl/AccessControl.tsx, packages/manager/src/views/Settings/components/AccessControl/AddMembers/AddMembersForm.tsx, packages/manager/src/views/Settings/components/AccessControl/ConfigureAccess/ConfigureAccess.tsx, packages/manager/src/views/Settings/components/AccessControl/ConfigureAccess/types.ts, packages/manager/src/views/Settings/components/AccessControl/EditAccess/EditMemberAccess.tsx
=> feat(Manger): Adding RBAC identifier for cmdb code update at property level in Settings

packages/manager/src/views/Settings/components/AccessControl/AccessControl.tsx
=> feat(Manger): Fixing lint issue

packages/api/src/server/environment/service/factory.ts
Subject: fix(api) : build path changed
1. build path changed
NO
<details>
</details>
=> fix(api) : build path changed

packages/manager/src/services/rbac/types.ts, packages/manager/src/views/Settings/components/AccessControl/AccessControl.tsx, packages/manager/src/views/Settings/components/AccessControl/AddMembers/AddMembersForm.tsx, packages/manager/src/views/Settings/components/AccessControl/ConfigureAccess/ConfigureAccess.tsx, packages/manager/src/views/Settings/components/AccessControl/ConfigureAccess/types.ts, packages/manager/src/views/Settings/components/AccessControl/EditAccess/EditMemberAccess.tsx
=> feat(Manger): Undoing CMDB code changes for property and RBAC

packages/manager/src/views/Settings/components/CmdbDetails/CmdbDetails.tsx
=> feat(Manger): Removing edit cmdb for property

packages/api/src/server/analytics/controller.ts, packages/api/src/server/analytics/service/factory.ts, packages/api/src/server/analytics/service/index.ts
Subject: feat(api) : count for the source analytics added
1. Analytics count added for the source and actions
NO
<details>
</details>
=> feat(api) : count for the source analytics added

packages/api/src/configuration/index.ts, packages/api/src/repository/mongo/model/application.ts, packages/api/src/server/application/entity.ts, packages/api/src/server/application/request.dto.ts, packages/api/src/server/application/service/factory.ts, packages/api/src/server/application/service/index.ts
Subject: configurations added for the SSR Deployment
1. requiredCpu, requiredMemory, limitCpu, limitMemory, replicas added
2. API modification for the deployment api
NO
<details>
</details>
=> chore(api) : Memory, Replicas, CPU limit & req added for the containerized deployment

packages/manager/src/views/WebPropertyDetailPage/components/SSR/ConfigureSSRForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/SSR/SsrForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ReviewSection.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/options.ts, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx
`WorkFlow`
1. New Application Configuration: Added fields for CPU required, memory required, memory limit, and CPU limit, along with replicas, for new applications.
2. Configuration Form Changes: Implemented the same updates for the configuration form to ensure consistency across forms
`SSR:`
1. New Application Form: Integrated CPU required, memory required, memory limit, and replicas fields into the new application form.
2. Configuration Form Changes: Implemented the same updates for the configuration form to ensure consistency across forms
5. 
<details>
</details>
=> feat(Manger): adding MP+ configuration to the new and reconfigured application form for WF3.0 and SSR.

packages/manager/src/views/DashboardPage/components/Analytics/Analytics.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ConfigureWorkflowForm.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/ReviewSection.tsx, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/options.ts, packages/manager/src/views/WebPropertyDetailPage/components/workflow3.0/workflow3.tsx
=> Fix(Manager) : Fixing form labels and dropdown values for mp+ configuration section

catalog-info.yml, catalog/systems/SPAship.yml, packages/api/catalog-info.yml, packages/cli/catalog-info.yml, packages/manager/catalog-info.yml
Follow the steps to create the PR:
Subject: "feat/fix/docs(#issue_id): <PR Subject>"
Assignees: "Developers"
Projects: ""
-->
<details>
</details>
=> chore(config): Updating catalog yamls for cleanup

catalog-info.yaml, catalog/systems/SPAship.yaml, packages/api/catalog-info.yaml, packages/cli/catalog-info.yaml, packages/manager/catalog-info.yaml
=> chore(config): Adding owner to backstage config yamls

packages/api/src/server/application/service/index.ts
Subject: pod updation issue resolved
1. pod updation issue resolved
NO
<details>
</details>
=> fix(api): pod updation issue resolved

packages/api/src/app.module.ts, packages/api/src/configuration/index.ts, packages/api/src/server/auth/guard.ts, packages/api/src/server/feedback/dto.ts, packages/api/src/server/health/controller.ts, packages/api/src/server/health/service/index.ts, packages/api/src/server/proxy/controller.ts, packages/api/src/server/proxy/service/index.ts, packages/api/src/server/proxy/service/module.ts
Subject: feat(api): proxy service added
1. proxy service added for statuspage
NO
<details>
</details>
=> feat(api): proxy service added
